import type { PracticeQuestion } from "./lessons";

export interface PracticeBankQuestion extends PracticeQuestion {
  topic: string;
  difficulty: "easy" | "medium" | "hard" | "very_hard";
}

export const PRACTICE_QUESTIONS: PracticeBankQuestion[] = [
  // Math - Algebra
  { id: "pq1", topic: "algebra", difficulty: "easy", question: "Solve: 5x - 3 = 12", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "5x = 15, so x = 3." },
  { id: "pq2", topic: "algebra", difficulty: "easy", question: "If 2(x + 4) = 18, then x = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "6" }, { key: "C", text: "7" }, { key: "D", text: "8" }], correctKey: "A", explanation: "2x + 8 = 18 → 2x = 10 → x = 5." },
  { id: "pq3", topic: "algebra", difficulty: "medium", question: "For what value of k does 3x + ky = 6 have slope -2?", options: [{ key: "A", text: "-6" }, { key: "B", text: "-3/2" }, { key: "C", text: "3/2" }, { key: "D", text: "6" }], correctKey: "C", explanation: "Slope = -3/k = -2, so k = 3/2." },
  { id: "pq4", topic: "algebra", difficulty: "medium", question: "If x² = 49, what is |x|?", options: [{ key: "A", text: "7" }, { key: "B", text: "49" }, { key: "C", text: "±7" }, { key: "D", text: "7 or -7" }], correctKey: "A", explanation: "|x| is the absolute value, so |7| = |-7| = 7." },
  { id: "pq5", topic: "algebra", difficulty: "hard", question: "If a + b = 10 and ab = 21, what is a² + b²?", options: [{ key: "A", text: "58" }, { key: "B", text: "79" }, { key: "C", text: "100" }, { key: "D", text: "121" }], correctKey: "A", explanation: "(a+b)² = a²+2ab+b². So 100 = a²+b²+42, hence a²+b² = 58." },
  // Math - Quadratics
  { id: "pq6", topic: "quadratics", difficulty: "easy", question: "What are the roots of x² - 9 = 0?", options: [{ key: "A", text: "3 only" }, { key: "B", text: "-3 only" }, { key: "C", text: "3 and -3" }, { key: "D", text: "9 and -9" }], correctKey: "C", explanation: "x² = 9 → x = ±3." },
  { id: "pq7", topic: "quadratics", difficulty: "medium", question: "The vertex of y = x² - 4x + 3 is at x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "B", explanation: "Vertex x = -b/(2a) = 4/2 = 2." },
  { id: "pq8", topic: "quadratics", difficulty: "hard", question: "For x² - 6x + c = 0 to have one real root, c = ?", options: [{ key: "A", text: "6" }, { key: "B", text: "9" }, { key: "C", text: "12" }, { key: "D", text: "18" }], correctKey: "B", explanation: "Discriminant b²-4ac = 0: 36-4c = 0, so c = 9." },
  // Math - Functions
  { id: "pq9", topic: "functions", difficulty: "easy", question: "If f(x) = x² + 1, then f(-2) = ?", options: [{ key: "A", text: "-3" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "7" }], correctKey: "C", explanation: "f(-2) = (-2)² + 1 = 4 + 1 = 5." },
  { id: "pq10", topic: "functions", difficulty: "medium", question: "If f(x) = 2x - 1 and g(x) = x + 3, what is f(g(2))?", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "9" }, { key: "D", text: "11" }], correctKey: "C", explanation: "g(2)=5, f(5)=2(5)-1=9." },
  // Math - Data
  { id: "pq11", topic: "data", difficulty: "easy", question: "Mean of 4, 6, 8, 10?", options: [{ key: "A", text: "6" }, { key: "B", text: "7" }, { key: "C", text: "8" }, { key: "D", text: "9" }], correctKey: "B", explanation: "(4+6+8+10)/4 = 28/4 = 7." },
  { id: "pq12", topic: "data", difficulty: "medium", question: "Data: 2, 4, 6, 6, 10. What is the mode?", options: [{ key: "A", text: "4" }, { key: "B", text: "5.6" }, { key: "C", text: "6" }, { key: "D", text: "10" }], correctKey: "C", explanation: "Mode is the most frequent value: 6." },
  // Math - Geometry
  { id: "pq13", topic: "geometry", difficulty: "easy", question: "Area of a circle with radius 5?", options: [{ key: "A", text: "10π" }, { key: "B", text: "25π" }, { key: "C", text: "50π" }, { key: "D", text: "100π" }], correctKey: "B", explanation: "A = πr² = π(25) = 25π." },
  { id: "pq14", topic: "geometry", difficulty: "medium", question: "A 30-60-90 triangle has short leg 4. What is the hypotenuse?", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "8" }, { key: "D", text: "12" }], correctKey: "C", explanation: "Hypotenuse = 2 × short leg = 8." },
  // Reading - Evidence
  { id: "pq15", topic: "evidence", difficulty: "easy", question: "The best evidence for an answer typically:", options: [{ key: "A", text: "Restates the question" }, { key: "B", text: "Directly supports the claim" }, { key: "C", text: "Is the longest sentence" }, { key: "D", text: "Uses emotional language" }], correctKey: "B", explanation: "Evidence must directly support your answer choice." },
  { id: "pq16", topic: "evidence", difficulty: "medium", question: "Paired evidence questions on the SAT often:", options: [{ key: "A", text: "Have no wrong answers" }, { key: "B", text: "Link back to your previous answer" }, { key: "C", text: "Require outside knowledge" }, { key: "D", text: "Test vocabulary only" }], correctKey: "B", explanation: "Evidence must support the answer you chose in the prior question." },
  // Reading - Words in Context
  { id: "pq17", topic: "words", difficulty: "easy", question: "In 'a fleeting moment,' fleeting means:", options: [{ key: "A", text: "lasting" }, { key: "B", text: "brief" }, { key: "C", text: "bright" }, { key: "D", text: "slow" }], correctKey: "B", explanation: "Fleeting means short-lived or brief." },
  { id: "pq18", topic: "words", difficulty: "medium", question: "In 'her words were equivocal,' equivocal means:", options: [{ key: "A", text: "clear" }, { key: "B", text: "ambiguous" }, { key: "C", text: "harsh" }, { key: "D", text: "kind" }], correctKey: "B", explanation: "Equivocal means ambiguous or open to multiple interpretations." },
  // Grammar
  { id: "pq19", topic: "grammar", difficulty: "easy", question: "Which is correct? 'Neither John nor his friends ___ going.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "was" }, { key: "D", text: "were" }], correctKey: "B", explanation: "With 'nor,' the verb agrees with the closer subject: 'friends' is plural, so 'are.'" },
  { id: "pq20", topic: "grammar", difficulty: "medium", question: "Which fixes the run-on? 'She ran fast she won the race.'", options: [{ key: "A", text: "She ran fast, she won the race." }, { key: "B", text: "She ran fast; she won the race." }, { key: "C", text: "She ran fast and she won the race." }, { key: "D", text: "Both B and C" }], correctKey: "D", explanation: "Semicolon or conjunction both fix the run-on." },
  // More Math
  { id: "pq21", topic: "algebra", difficulty: "easy", question: "Simplify: 3(x - 4) + 2x", options: [{ key: "A", text: "5x - 12" }, { key: "B", text: "5x - 4" }, { key: "C", text: "6x - 12" }, { key: "D", text: "6x - 4" }], correctKey: "A", explanation: "3x - 12 + 2x = 5x - 12." },
  { id: "pq22", topic: "algebra", difficulty: "medium", question: "If 2^x = 8, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "8" }], correctKey: "B", explanation: "8 = 2³, so x = 3." },
  { id: "pq23", topic: "algebra", difficulty: "medium", question: "Solve |2x - 4| = 10", options: [{ key: "A", text: "x = 7 only" }, { key: "B", text: "x = -3 only" }, { key: "C", text: "x = 7 or x = -3" }, { key: "D", text: "No solution" }], correctKey: "C", explanation: "2x-4=10 → x=7; 2x-4=-10 → x=-3." },
  { id: "pq24", topic: "quadratics", difficulty: "easy", question: "(x + 5)(x - 5) = ?", options: [{ key: "A", text: "x² - 25" }, { key: "B", text: "x² + 25" }, { key: "C", text: "x² - 10" }, { key: "D", text: "x² + 10x - 25" }], correctKey: "A", explanation: "Difference of squares: (x+5)(x-5) = x² - 25." },
  { id: "pq25", topic: "quadratics", difficulty: "hard", question: "For x² + bx + 16 to be a perfect square, b = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "8" }, { key: "C", text: "±8" }, { key: "D", text: "±4" }], correctKey: "C", explanation: "(x±4)² = x² ± 8x + 16, so b = ±8." },
  { id: "pq26", topic: "geometry", difficulty: "easy", question: "Perimeter of a square with side 7?", options: [{ key: "A", text: "14" }, { key: "B", text: "28" }, { key: "C", text: "49" }, { key: "D", text: "56" }], correctKey: "B", explanation: "P = 4s = 4(7) = 28." },
  { id: "pq27", topic: "geometry", difficulty: "medium", question: "Volume of a cylinder with r=3, h=4?", options: [{ key: "A", text: "12π" }, { key: "B", text: "24π" }, { key: "C", text: "36π" }, { key: "D", text: "48π" }], correctKey: "C", explanation: "V = πr²h = π(9)(4) = 36π." },
  { id: "pq28", topic: "data", difficulty: "hard", question: "If the mean of 5 numbers is 20 and four are 15, 20, 25, 20, the fifth is:", options: [{ key: "A", text: "15" }, { key: "B", text: "20" }, { key: "C", text: "25" }, { key: "D", text: "30" }], correctKey: "B", explanation: "Sum = 100, four sum to 80, so fifth = 20." },
  { id: "pq29", topic: "reading", difficulty: "medium", question: "The main purpose of an argumentative passage is to:", options: [{ key: "A", text: "Entertain" }, { key: "B", text: "Persuade" }, { key: "C", text: "Describe" }, { key: "D", text: "Narrate" }], correctKey: "B", explanation: "Argumentative writing aims to persuade." },
  { id: "pq30", topic: "transitions", difficulty: "easy", question: "Which shows addition? The experiment failed. ___, we learned from it.", options: [{ key: "A", text: "However" }, { key: "B", text: "Therefore" }, { key: "C", text: "Moreover" }, { key: "D", text: "Consequently" }], correctKey: "C", explanation: "Moreover adds related information." },
  // Algebra - more
  { id: "pq31", topic: "algebra", difficulty: "easy", question: "Solve: 4x + 2 = 14", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "4x = 12, so x = 3." },
  { id: "pq32", topic: "algebra", difficulty: "easy", question: "If 3x - 5 = 16, then x = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "6" }, { key: "C", text: "7" }, { key: "D", text: "8" }], correctKey: "C", explanation: "3x = 21, so x = 7." },
  { id: "pq33", topic: "algebra", difficulty: "easy", question: "Simplify: 2(x + 3) - 4x", options: [{ key: "A", text: "-2x + 6" }, { key: "B", text: "-2x + 3" }, { key: "C", text: "2x + 6" }, { key: "D", text: "6x + 6" }], correctKey: "A", explanation: "2x + 6 - 4x = -2x + 6." },
  { id: "pq34", topic: "algebra", difficulty: "medium", question: "If x/4 + x/3 = 7, then x = ?", options: [{ key: "A", text: "10" }, { key: "B", text: "12" }, { key: "C", text: "14" }, { key: "D", text: "16" }], correctKey: "B", explanation: "LCD 12: 3x + 4x = 84, so x = 12." },
  { id: "pq35", topic: "algebra", difficulty: "medium", question: "If 3^(x+1) = 81, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "81 = 3^4, so x+1 = 4, x = 3." },
  { id: "pq36", topic: "algebra", difficulty: "medium", question: "If 2x + y = 7 and x - y = 2, what is x?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "C", explanation: "Add equations: 3x = 9, so x = 3." },
  { id: "pq37", topic: "algebra", difficulty: "hard", question: "If (x-2)(x-3) = 0 and x > 2.5, what is x?", options: [{ key: "A", text: "2" }, { key: "B", text: "2.5" }, { key: "C", text: "3" }, { key: "D", text: "5" }], correctKey: "C", explanation: "Roots are 2 and 3; x > 2.5 so x = 3." },
  // Algebra continued
  { id: "pq38", topic: "algebra", difficulty: "easy", question: "Solve: x/2 = 9", options: [{ key: "A", text: "4.5" }, { key: "B", text: "7" }, { key: "C", text: "18" }, { key: "D", text: "11" }], correctKey: "C", explanation: "x = 9 × 2 = 18." },
  { id: "pq39", topic: "algebra", difficulty: "medium", question: "If √(x+1) = 4, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "15" }, { key: "C", text: "16" }, { key: "D", text: "17" }], correctKey: "B", explanation: "x+1 = 16, so x = 15." },
  { id: "pq40", topic: "algebra", difficulty: "hard", question: "If 2^x · 2^3 = 2^8, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "5" }, { key: "C", text: "8" }, { key: "D", text: "11" }], correctKey: "B", explanation: "2^(x+3) = 2^8, so x+3 = 8, x = 5." },
  // Quadratics
  { id: "pq41", topic: "quadratics", difficulty: "easy", question: "Factor: x² + 5x + 6", options: [{ key: "A", text: "(x+1)(x+6)" }, { key: "B", text: "(x+2)(x+3)" }, { key: "C", text: "(x+2)(x+4)" }, { key: "D", text: "(x+1)(x+5)" }], correctKey: "B", explanation: "x²+5x+6 = (x+2)(x+3)." },
  { id: "pq42", topic: "quadratics", difficulty: "medium", question: "What is the y-intercept of y = x² - 4x + 3?", options: [{ key: "A", text: "-4" }, { key: "B", text: "0" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "C", explanation: "y-intercept: set x=0, y = 3." },
  { id: "pq43", topic: "quadratics", difficulty: "hard", question: "The sum of the roots of x² - 7x + 12 = 0 is:", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "12" }, { key: "D", text: "19" }], correctKey: "B", explanation: "Sum of roots = -b/a = 7." },
  // Functions
  { id: "pq44", topic: "functions", difficulty: "easy", question: "If g(x) = x - 4, then g(10) = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "10" }, { key: "D", text: "14" }], correctKey: "B", explanation: "g(10) = 10 - 4 = 6." },
  { id: "pq45", topic: "functions", difficulty: "medium", question: "If f(x) = x² and g(x) = x + 1, then f(g(2)) = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "9" }, { key: "C", text: "10" }, { key: "D", text: "12" }], correctKey: "B", explanation: "g(2)=3, f(3)=9." },
  { id: "pq46", topic: "functions", difficulty: "hard", question: "If f(x) = 2x - 1, what is f⁻¹(5)?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "Solve 2x-1=5 → x=3." },
  // Data
  { id: "pq47", topic: "data", difficulty: "easy", question: "Median of 1, 3, 5, 7, 9?", options: [{ key: "A", text: "3" }, { key: "B", text: "5" }, { key: "C", text: "7" }, { key: "D", text: "25" }], correctKey: "B", explanation: "Middle value is 5." },
  { id: "pq48", topic: "data", difficulty: "medium", question: "Range of 2, 5, 8, 11, 14?", options: [{ key: "A", text: "6" }, { key: "B", text: "8" }, { key: "C", text: "12" }, { key: "D", text: "14" }], correctKey: "C", explanation: "Range = max - min = 14 - 2 = 12." },
  { id: "pq49", topic: "data", difficulty: "hard", question: "If mean of 6 numbers is 10 and five are 8, 9, 10, 11, 12, the sixth is:", options: [{ key: "A", text: "8" }, { key: "B", text: "10" }, { key: "C", text: "12" }, { key: "D", text: "14" }], correctKey: "B", explanation: "Sum=60, five sum to 50, so sixth = 10." },
  // Geometry
  { id: "pq50", topic: "geometry", difficulty: "easy", question: "Circumference of circle with radius 10?", options: [{ key: "A", text: "10π" }, { key: "B", text: "20π" }, { key: "C", text: "100π" }, { key: "D", text: "200π" }], correctKey: "B", explanation: "C = 2πr = 20π." },
  { id: "pq51", topic: "geometry", difficulty: "medium", question: "A 45-45-90 triangle has leg 5. Hypotenuse = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "5√2" }, { key: "C", text: "10" }, { key: "D", text: "25" }], correctKey: "B", explanation: "Hypotenuse = leg × √2 = 5√2." },
  { id: "pq52", topic: "geometry", difficulty: "hard", question: "Volume of a sphere with radius 3?", options: [{ key: "A", text: "9π" }, { key: "B", text: "12π" }, { key: "C", text: "36π" }, { key: "D", text: "108π" }], correctKey: "C", explanation: "V = (4/3)πr³ = (4/3)π(27) = 36π." },
  // Reading & Grammar
  { id: "pq53", topic: "evidence", difficulty: "easy", question: "Evidence questions ask you to:", options: [{ key: "A", text: "Guess the author's intent" }, { key: "B", text: "Find text that supports your answer" }, { key: "C", text: "Summarize the passage" }, { key: "D", text: "Identify the main idea" }], correctKey: "B", explanation: "Evidence must support your prior answer." },
  { id: "pq54", topic: "words", difficulty: "easy", question: "In 'a tenuous connection,' tenuous means:", options: [{ key: "A", text: "strong" }, { key: "B", text: "weak" }, { key: "C", text: "obvious" }, { key: "D", text: "permanent" }], correctKey: "B", explanation: "Tenuous means weak or insubstantial." },
  { id: "pq55", topic: "grammar", difficulty: "easy", question: "Which is correct? 'The team ___ playing well.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "were" }, { key: "D", text: "been" }], correctKey: "A", explanation: "Collective noun 'team' is singular in US English." },
  { id: "pq56", topic: "grammar", difficulty: "medium", question: "Which fixes the comma splice? 'I ran, I was late.'", options: [{ key: "A", text: "I ran, I was late." }, { key: "B", text: "I ran; I was late." }, { key: "C", text: "I ran I was late." }, { key: "D", text: "I ran, because I was late." }], correctKey: "B", explanation: "Semicolon joins two independent clauses." },
  { id: "pq57", topic: "transitions", difficulty: "medium", question: "Which shows contrast? 'It rained. ___, the game continued.'", options: [{ key: "A", text: "Therefore" }, { key: "B", text: "Moreover" }, { key: "C", text: "Nevertheless" }, { key: "D", text: "Consequently" }], correctKey: "C", explanation: "Nevertheless shows contrast." },
  // More algebra
  { id: "pq58", topic: "algebra", difficulty: "easy", question: "If 6x = 18, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "12" }, { key: "D", text: "24" }], correctKey: "B", explanation: "x = 18/6 = 3." },
  { id: "pq59", topic: "algebra", difficulty: "easy", question: "Simplify: -2(x - 3) + 4", options: [{ key: "A", text: "-2x + 10" }, { key: "B", text: "-2x - 2" }, { key: "C", text: "-2x + 2" }, { key: "D", text: "2x + 10" }], correctKey: "A", explanation: "-2x + 6 + 4 = -2x + 10." },
  { id: "pq60", topic: "algebra", difficulty: "medium", question: "If 1/x + 1/2 = 1, then x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "B", explanation: "1/x = 1/2, so x = 2." },
  { id: "pq61", topic: "algebra", difficulty: "hard", question: "If x + 1/x = 3, then x² + 1/x² = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "9" }, { key: "D", text: "11" }], correctKey: "B", explanation: "(x+1/x)² = x²+2+1/x² = 9, so x²+1/x² = 7." },
  // More quadratics
  { id: "pq62", topic: "quadratics", difficulty: "easy", question: "x² - 16 = 0 has solutions:", options: [{ key: "A", text: "4 only" }, { key: "B", text: "-4 only" }, { key: "C", text: "4 and -4" }, { key: "D", text: "8 and -8" }], correctKey: "C", explanation: "x² = 16 → x = ±4." },
  { id: "pq63", topic: "quadratics", difficulty: "medium", question: "Product of roots of x² - 5x + 6 = 0?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "D", explanation: "Product = c/a = 6." },
  { id: "pq64", topic: "quadratics", difficulty: "hard", question: "For x² + px + 9 = 0 to have one real root, |p| = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "6" }, { key: "C", text: "9" }, { key: "D", text: "12" }], correctKey: "B", explanation: "Discriminant = p² - 36 = 0, so p = ±6." },
  // More functions
  { id: "pq65", topic: "functions", difficulty: "easy", question: "If h(x) = 3x + 2, then h(0) = ?", options: [{ key: "A", text: "0" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "5" }], correctKey: "B", explanation: "h(0) = 3(0) + 2 = 2." },
  { id: "pq66", topic: "functions", difficulty: "medium", question: "If f(x) = x + 1 and f(a) = 5, then a = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "4" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "B", explanation: "a + 1 = 5, so a = 4." },
  { id: "pq67", topic: "functions", difficulty: "hard", question: "If f(x) = 2x² - 3, then f(-1) = ?", options: [{ key: "A", text: "-5" }, { key: "B", text: "-1" }, { key: "C", text: "1" }, { key: "D", text: "5" }], correctKey: "B", explanation: "f(-1) = 2(1) - 3 = -1." },
  // More data
  { id: "pq68", topic: "data", difficulty: "easy", question: "Mode of 1, 2, 2, 3, 3, 3, 4?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "2.5" }, { key: "D", text: "4" }], correctKey: "B", explanation: "3 appears most often." },
  { id: "pq69", topic: "data", difficulty: "medium", question: "If 5 numbers have mean 8 and sum 40, how many numbers?", options: [{ key: "A", text: "4" }, { key: "B", text: "5" }, { key: "C", text: "6" }, { key: "D", text: "8" }], correctKey: "B", explanation: "Mean = sum/n, 8 = 40/n, n = 5." },
  { id: "pq70", topic: "data", difficulty: "hard", question: "5 numbers have mean 10. One number increases by 20. New mean?", options: [{ key: "A", text: "12" }, { key: "B", text: "14" }, { key: "C", text: "16" }, { key: "D", text: "18" }], correctKey: "B", explanation: "Old sum = 50. New sum = 50 + 20 = 70. New mean = 70/5 = 14." },
  // Geometry & more
  { id: "pq71", topic: "geometry", difficulty: "easy", question: "Area of triangle with base 6, height 4?", options: [{ key: "A", text: "10" }, { key: "B", text: "12" }, { key: "C", text: "24" }, { key: "D", text: "48" }], correctKey: "B", explanation: "A = ½bh = ½(6)(4) = 12." },
  { id: "pq72", topic: "geometry", difficulty: "medium", question: "Surface area of cube with edge 3?", options: [{ key: "A", text: "27" }, { key: "B", text: "54" }, { key: "C", text: "81" }, { key: "D", text: "108" }], correctKey: "B", explanation: "6 faces × 9 = 54." },
  { id: "pq73", topic: "geometry", difficulty: "hard", question: "A right triangle has legs 5 and 12. Hypotenuse?", options: [{ key: "A", text: "13" }, { key: "B", text: "17" }, { key: "C", text: "√119" }, { key: "D", text: "7" }], correctKey: "A", explanation: "5²+12²=25+144=169=13²." },
  // Reading
  { id: "pq74", topic: "reading", difficulty: "easy", question: "A narrative passage mainly:", options: [{ key: "A", text: "Tells a story" }, { key: "B", text: "Argues a point" }, { key: "C", text: "Explains a process" }, { key: "D", text: "Compares topics" }], correctKey: "A", explanation: "Narrative = story." },
  { id: "pq75", topic: "reading", difficulty: "medium", question: "When asked about author's purpose, consider:", options: [{ key: "A", text: "Only the first paragraph" }, { key: "B", text: "The whole passage" }, { key: "C", text: "Just the conclusion" }, { key: "D", text: "The title only" }], correctKey: "B", explanation: "Purpose is shown throughout the passage." },
  { id: "pq76", topic: "words", difficulty: "medium", question: "In 'his sardonic smile,' sardonic means:", options: [{ key: "A", text: "warm" }, { key: "B", text: "mocking" }, { key: "C", text: "shy" }, { key: "D", text: "confused" }], correctKey: "B", explanation: "Sardonic = mocking or cynical." },
  { id: "pq77", topic: "grammar", difficulty: "medium", question: "Which uses parallel structure? He likes running, swimming, and ___.", options: [{ key: "A", text: "to bike" }, { key: "B", text: "biking" }, { key: "C", text: "bikes" }, { key: "D", text: "biked" }], correctKey: "B", explanation: "running, swimming, biking—all -ing." },
  { id: "pq78", topic: "evidence", difficulty: "medium", question: "Wrong evidence choices often:", options: [{ key: "A", text: "Support your answer well" }, { key: "B", text: "Sound relevant but don't prove the answer" }, { key: "C", text: "Come from the right paragraph" }, { key: "D", text: "Are too short" }], correctKey: "B", explanation: "Wrong answers sound good but don't actually support your choice." },
  { id: "pq79", topic: "transitions", difficulty: "easy", question: "Which shows cause and effect? ___ it rained, we stayed inside.", options: [{ key: "A", text: "However" }, { key: "B", text: "Because" }, { key: "C", text: "Although" }, { key: "D", text: "Meanwhile" }], correctKey: "B", explanation: "Because shows cause (rain) and effect (stayed inside)." },
  { id: "pq80", topic: "algebra", difficulty: "easy", question: "Solve: 7 - 2x = 1", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "-2x = -6, so x = 3." },
  { id: "pq81", topic: "algebra", difficulty: "medium", question: "If (x-1)(x+2) = 0, which is a solution?", options: [{ key: "A", text: "-1" }, { key: "B", text: "0" }, { key: "C", text: "1" }, { key: "D", text: "2" }], correctKey: "C", explanation: "Roots are 1 and -2; 1 is a solution." },
  { id: "pq82", topic: "quadratics", difficulty: "easy", question: "(x+4)² = ?", options: [{ key: "A", text: "x²+16" }, { key: "B", text: "x²+8x+16" }, { key: "C", text: "x²+4x+16" }, { key: "D", text: "x²+8" }], correctKey: "B", explanation: "(x+4)² = x² + 8x + 16." },
  { id: "pq83", topic: "quadratics", difficulty: "medium", question: "Axis of symmetry of y = x² - 6x + 5 is x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "B", explanation: "x = -b/(2a) = 6/2 = 3." },
  { id: "pq84", topic: "functions", difficulty: "easy", question: "If p(x) = 5 - x, then p(3) = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "8" }], correctKey: "A", explanation: "p(3) = 5 - 3 = 2." },
  { id: "pq85", topic: "data", difficulty: "easy", question: "Mean of 10, 20, 30?", options: [{ key: "A", text: "15" }, { key: "B", text: "20" }, { key: "C", text: "25" }, { key: "D", text: "60" }], correctKey: "B", explanation: "(10+20+30)/3 = 20." },
  { id: "pq86", topic: "geometry", difficulty: "easy", question: "Volume of cube with edge 4?", options: [{ key: "A", text: "12" }, { key: "B", text: "16" }, { key: "C", text: "64" }, { key: "D", text: "96" }], correctKey: "C", explanation: "V = s³ = 4³ = 64." },
  { id: "pq87", topic: "grammar", difficulty: "easy", question: "Which is correct? 'She and I ___ going.'", options: [{ key: "A", text: "am" }, { key: "B", text: "is" }, { key: "C", text: "are" }, { key: "D", text: "was" }], correctKey: "C", explanation: "Compound subject 'She and I' is plural." },
  { id: "pq88", topic: "words", difficulty: "easy", question: "In 'a prolific writer,' prolific means:", options: [{ key: "A", text: "lazy" }, { key: "B", text: "productive" }, { key: "C", text: "famous" }, { key: "D", text: "old" }], correctKey: "B", explanation: "Prolific = producing much." },
  { id: "pq89", topic: "algebra", difficulty: "hard", question: "If 3x - 2 = 2x + 5, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "5" }, { key: "C", text: "7" }, { key: "D", text: "9" }], correctKey: "C", explanation: "3x - 2x = 5 + 2, so x = 7." },
  { id: "pq90", topic: "algebra", difficulty: "medium", question: "If 4(x - 2) = 2(x + 4), then x = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "8" }, { key: "D", text: "10" }], correctKey: "C", explanation: "4x-8=2x+8, 2x=16, x=8." },
  { id: "pq91", topic: "quadratics", difficulty: "hard", question: "Discriminant of x² + 4x + 4 = 0?", options: [{ key: "A", text: "0" }, { key: "B", text: "4" }, { key: "C", text: "8" }, { key: "D", text: "16" }], correctKey: "A", explanation: "b²-4ac = 16-16 = 0 (perfect square)." },
  { id: "pq92", topic: "geometry", difficulty: "medium", question: "Area of trapezoid with bases 4 and 6, height 5?", options: [{ key: "A", text: "20" }, { key: "B", text: "25" }, { key: "C", text: "30" }, { key: "D", text: "50" }], correctKey: "B", explanation: "A = ½(4+6)(5) = 25." },
  { id: "pq93", topic: "reading", difficulty: "hard", question: "Inference questions require:", options: [{ key: "A", text: "Exact quotes from the text" }, { key: "B", text: "Logical conclusions from evidence" }, { key: "C", text: "Outside knowledge only" }, { key: "D", text: "The first sentence" }], correctKey: "B", explanation: "Inferences are supported by the passage." },
  { id: "pq94", topic: "grammar", difficulty: "hard", question: "Which is correct? 'The data ___ conclusive.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "was" }, { key: "D", text: "A or B" }], correctKey: "D", explanation: "Data can be singular or plural; both are accepted." },
  { id: "pq95", topic: "transitions", difficulty: "hard", question: "Which signals a conclusion? ___ the evidence supports the theory.", options: [{ key: "A", text: "Furthermore" }, { key: "B", text: "In conclusion" }, { key: "C", text: "For example" }, { key: "D", text: "Similarly" }], correctKey: "B", explanation: "In conclusion signals a summary or ending." },
  { id: "pq96", topic: "algebra", difficulty: "easy", question: "If x + 5 = 12, then x = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "12" }, { key: "D", text: "17" }], correctKey: "B", explanation: "x = 12 - 5 = 7." },
  { id: "pq97", topic: "functions", difficulty: "medium", question: "Domain of f(x) = 1/(x-2) excludes:", options: [{ key: "A", text: "0" }, { key: "B", text: "1" }, { key: "C", text: "2" }, { key: "D", text: "3" }], correctKey: "C", explanation: "x=2 makes the denominator zero." },
  { id: "pq98", topic: "data", difficulty: "medium", question: "Median of 1, 2, 3, 4, 5, 6?", options: [{ key: "A", text: "3" }, { key: "B", text: "3.5" }, { key: "C", text: "4" }, { key: "D", text: "4.5" }], correctKey: "B", explanation: "Average of 3 and 4 = 3.5." },
  { id: "pq99", topic: "evidence", difficulty: "hard", question: "Best strategy for paired evidence questions:", options: [{ key: "A", text: "Pick evidence first" }, { key: "B", text: "Answer main question first, then find evidence" }, { key: "C", text: "Skip the main question" }, { key: "D", text: "Guess both" }], correctKey: "B", explanation: "Answer first, then find the line that proves it." },
  { id: "pq100", topic: "words", difficulty: "hard", question: "In 'an ambivalent response,' ambivalent means:", options: [{ key: "A", text: "clear" }, { key: "B", text: "mixed feelings" }, { key: "C", text: "negative" }, { key: "D", text: "enthusiastic" }], correctKey: "B", explanation: "Ambivalent = having mixed or conflicting feelings." },
  // New subcategories: Inequalities
  { id: "pq101", topic: "inequalities", difficulty: "easy", question: "Solve: 2x + 3 > 9", options: [{ key: "A", text: "x > 3" }, { key: "B", text: "x > 6" }, { key: "C", text: "x < 3" }, { key: "D", text: "x > 4" }], correctKey: "A", explanation: "2x > 6, so x > 3." },
  { id: "pq102", topic: "inequalities", difficulty: "medium", question: "Solve: -3x + 6 ≥ 12", options: [{ key: "A", text: "x ≥ -2" }, { key: "B", text: "x ≤ -2" }, { key: "C", text: "x ≥ 2" }, { key: "D", text: "x ≤ 2" }], correctKey: "B", explanation: "-3x ≥ 6; dividing by -3 flips the sign: x ≤ -2." },
  { id: "pq103", topic: "inequalities", difficulty: "hard", question: "For what x is |x - 4| < 7?", options: [{ key: "A", text: "x < 11" }, { key: "B", text: "-3 < x < 11" }, { key: "C", text: "x > -3" }, { key: "D", text: "x < -3 or x > 11" }], correctKey: "B", explanation: "-7 < x - 4 < 7, so -3 < x < 11." },
  { id: "pq104", topic: "inequalities", difficulty: "very_hard", question: "How many integer solutions does 1 ≤ 2x - 3 < 9 have?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "C", explanation: "4 ≤ 2x < 12 → 2 ≤ x < 6. Integers: 2, 3, 4, 5 → 4 solutions." },
  // Exponentials
  { id: "pq105", topic: "exponentials", difficulty: "easy", question: "If 2^x = 16, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "4" }, { key: "C", text: "8" }, { key: "D", text: "16" }], correctKey: "B", explanation: "16 = 2^4, so x = 4." },
  { id: "pq106", topic: "exponentials", difficulty: "medium", question: "A population doubles every 5 years. After 15 years, it is how many times the original?", options: [{ key: "A", text: "3" }, { key: "B", text: "6" }, { key: "C", text: "8" }, { key: "D", text: "15" }], correctKey: "C", explanation: "Doubles 3 times in 15 years: 2^3 = 8." },
  { id: "pq107", topic: "exponentials", difficulty: "hard", question: "If 3^(2x) = 81, then x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "B", explanation: "81 = 3^4, so 2x = 4, x = 2." },
  { id: "pq108", topic: "exponentials", difficulty: "very_hard", question: "An investment doubles in 10 years with annual compounding. Nearest 0.1%, the annual rate is:", options: [{ key: "A", text: "6.0%" }, { key: "B", text: "7.0%" }, { key: "C", text: "7.2%" }, { key: "D", text: "10.0%" }], correctKey: "C", explanation: "(1+r)^10 = 2 → 1+r = 2^0.1 ≈ 1.0718 → r ≈ 7.2%." },
  // Trigonometry
  { id: "pq109", topic: "trigonometry", difficulty: "easy", question: "In a right triangle with legs 3 and 4, sin(θ) for the angle opposite 3 is:", options: [{ key: "A", text: "3/4" }, { key: "B", text: "3/5" }, { key: "C", text: "4/5" }, { key: "D", text: "5/3" }], correctKey: "B", explanation: "Hypotenuse = 5. sin = opposite/hyp = 3/5." },
  { id: "pq110", topic: "trigonometry", difficulty: "medium", question: "A 30-60-90 triangle has hypotenuse 10. The longer leg is:", options: [{ key: "A", text: "5" }, { key: "B", text: "5√3" }, { key: "C", text: "10√3" }, { key: "D", text: "20" }], correctKey: "B", explanation: "Short leg = 5, longer leg = 5√3." },
  { id: "pq111", topic: "trigonometry", difficulty: "hard", question: "Circle radius 5, center (0,0). Point (3,4) is:", options: [{ key: "A", text: "inside" }, { key: "B", text: "on the circle" }, { key: "C", text: "outside" }, { key: "D", text: "at center" }], correctKey: "B", explanation: "Distance √(9+16)=5 = radius, so on the circle." },
  { id: "pq112", topic: "trigonometry", difficulty: "very_hard", question: "For 0° < θ < 90°, if sin θ = 2/3, then cos θ = ?", options: [{ key: "A", text: "1/3" }, { key: "B", text: "√5/3" }, { key: "C", text: "2/3" }, { key: "D", text: "√13/3" }], correctKey: "B", explanation: "sin²+cos²=1 → cos²=1-4/9=5/9 → cos=√5/3 (positive in first quadrant)." },
  // Word problems
  { id: "pq113", topic: "word-problems", difficulty: "easy", question: "Tickets $6 adults, $4 kids. 20 tickets sold for $100. How many adult tickets?", options: [{ key: "A", text: "8" }, { key: "B", text: "10" }, { key: "C", text: "12" }, { key: "D", text: "15" }], correctKey: "B", explanation: "a+k=20, 6a+4k=100 → 6a+4(20-a)=100 → 2a=20 → a=10." },
  { id: "pq114", topic: "word-problems", difficulty: "medium", question: "A car travels 240 mi at 60 mph. Return at 40 mph. Average speed for round trip?", options: [{ key: "A", text: "50" }, { key: "B", text: "48" }, { key: "C", text: "45" }, { key: "D", text: "55" }], correctKey: "B", explanation: "Out: 4 hr. Back: 6 hr. Total 480 mi / 10 hr = 48 mph." },
  { id: "pq115", topic: "word-problems", difficulty: "hard", question: "Pipe A fills a tank in 6 hr, B in 4 hr. Together they fill it in how many hours?", options: [{ key: "A", text: "2" }, { key: "B", text: "2.4" }, { key: "C", text: "5" }, { key: "D", text: "10" }], correctKey: "B", explanation: "Rates 1/6+1/4=5/12 per hr → 12/5=2.4 hr." },
  { id: "pq116", topic: "word-problems", difficulty: "very_hard", question: "A 30% solution and 60% solution are mixed to get 20 L of 45% solution. How many L of 60%?", options: [{ key: "A", text: "6" }, { key: "B", text: "8" }, { key: "C", text: "10" }, { key: "D", text: "12" }], correctKey: "C", explanation: "0.30(20-x)+0.60x=0.45(20) → 6-0.3x+0.6x=9 → 0.3x=3 → x=10." },
  // Advanced math
  { id: "pq117", topic: "advanced-math", difficulty: "medium", question: "When P(x)=x³-2x²+ax-4 is divided by (x-2), remainder is 0. a = ?", options: [{ key: "A", text: "0" }, { key: "B", text: "2" }, { key: "C", text: "4" }, { key: "D", text: "6" }], correctKey: "B", explanation: "P(2)=8-8+2a-4=0 → 2a=4 → a=2." },
  { id: "pq118", topic: "advanced-math", difficulty: "hard", question: "Solve √(3x+1) = x - 1. Which value works?", options: [{ key: "A", text: "0" }, { key: "B", text: "1" }, { key: "C", text: "3" }, { key: "D", text: "5" }], correctKey: "D", explanation: "Square: 3x+1=x²-2x+1 → x²-5x=0 → x=0 or 5. Check x=5: √16=4, 5-1=4 ✓. x=0 gives 1=-1 (extraneous). So x=5." },
  { id: "pq119", topic: "advanced-math", difficulty: "very_hard", question: "For x²+px+16=0 to have one real root, |p| = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "8" }, { key: "C", text: "12" }, { key: "D", text: "16" }], correctKey: "B", explanation: "Discriminant p²-64=0 → p=±8, so |p|=8." },
  { id: "pq120", topic: "advanced-math", difficulty: "very_hard", question: "log₂(x)+log₂(x+2)=3. What is x?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "4" }, { key: "D", text: "6" }], correctKey: "B", explanation: "log₂(x(x+2))=3 → x²+2x=8 → x²+2x-8=0 → x=2 or -4; x>0 so x=2." },
  // Main idea (reading)
  { id: "pq121", topic: "main-idea", difficulty: "easy", question: "The main idea of a passage is best found by:", options: [{ key: "A", text: "Reading only the first sentence" }, { key: "B", text: "Synthesizing the whole passage" }, { key: "C", text: "Looking at the title only" }, { key: "D", text: "Reading only the last paragraph" }], correctKey: "B", explanation: "Main idea comes from the whole passage." },
  { id: "pq122", topic: "main-idea", difficulty: "medium", question: "A wrong main-idea answer often:", options: [{ key: "A", text: "Matches the whole passage" }, { key: "B", text: "Focuses on one detail or paragraph" }, { key: "C", text: "Is too broad" }, { key: "D", text: "Both B and C" }], correctKey: "D", explanation: "Wrong answers are often too narrow (one detail) or too broad." },
  { id: "pq123", topic: "main-idea", difficulty: "hard", question: "The passage argues that policy X failed. The main idea is:", options: [{ key: "A", text: "Policy X was proposed in 2020." }, { key: "B", text: "Policy X did not achieve its goals." }, { key: "C", text: "Many people debated policy X." }, { key: "D", text: "Policy X was expensive." }], correctKey: "B", explanation: "Main idea = primary claim; here that the policy failed." },
  { id: "pq124", topic: "main-idea", difficulty: "very_hard", question: "Two passages: P1 supports funding; P2 opposes it. What would both agree on?", options: [{ key: "A", text: "Funding should increase." }, { key: "B", text: "Funding should decrease." }, { key: "C", text: "The issue of funding is important." }, { key: "D", text: "Neither passage discusses funding." }], correctKey: "C", explanation: "Both can agree the issue matters without agreeing on the solution." },
  // Tone
  { id: "pq125", topic: "tone", difficulty: "easy", question: "'Well-intentioned but misguided' suggests a tone of:", options: [{ key: "A", text: "Full support" }, { key: "B", text: "Dismissive contempt" }, { key: "C", text: "Critical but acknowledging intent" }, { key: "D", text: "Neutral" }], correctKey: "C", explanation: "Acknowledges good intent but criticizes the outcome." },
  { id: "pq126", topic: "tone", difficulty: "medium", question: "The author describes a study as 'flawed yet influential.' Tone is:", options: [{ key: "A", text: "Enthusiastic" }, { key: "B", text: "Qualified or mixed" }, { key: "C", text: "Indifferent" }, { key: "D", text: "Hostile" }], correctKey: "B", explanation: "Qualified: acknowledges both criticism (flawed) and impact (influential)." },
  { id: "pq127", topic: "tone", difficulty: "hard", question: "Passage shifts from hopeful to skeptical. The shift serves to:", options: [{ key: "A", text: "Repeat the main idea" }, { key: "B", text: "Introduce then qualify or challenge the initial view" }, { key: "C", text: "Change the topic" }, { key: "D", text: "Add a new character" }], correctKey: "B", explanation: "Shift from hopeful to skeptical qualifies or challenges the opening." },
  { id: "pq128", topic: "tone", difficulty: "very_hard", question: "Author cites a critic then presents counterevidence. Author's tone toward the critic is:", options: [{ key: "A", text: "Admiring" }, { key: "B", text: "Dismissive" }, { key: "C", text: "Respectful but disagreeing" }, { key: "D", text: "Indifferent" }], correctKey: "C", explanation: "Presenting counterevidence shows disagreement while citing suggests respect." },
  // Rhetoric
  { id: "pq129", topic: "rhetoric", difficulty: "easy", question: "The author includes a quotation primarily to:", options: [{ key: "A", text: "Fill space" }, { key: "B", text: "Support or illustrate a point" }, { key: "C", text: "Contradict the main idea" }, { key: "D", text: "End the passage" }], correctKey: "B", explanation: "Quotations typically support or illustrate the argument." },
  { id: "pq130", topic: "rhetoric", difficulty: "medium", question: "A paragraph that presents an opposing view before the author's response mainly:", options: [{ key: "A", text: "Introduces the topic" }, { key: "B", text: "Presents a counterargument to address" }, { key: "C", text: "Concludes the passage" }, { key: "D", text: "Provides a personal anecdote" }], correctKey: "B", explanation: "Opposing view = counterargument that the author then addresses." },
  { id: "pq131", topic: "rhetoric", difficulty: "hard", question: "Which most weakens: 'Only A has won; so A will win again'?", options: [{ key: "A", text: "A has strong players." }, { key: "B", text: "Past winners often don't repeat." }, { key: "C", text: "A's coach is experienced." }, { key: "D", text: "The title is prestigious." }], correctKey: "B", explanation: "B undermines the assumption that past success predicts future success." },
  { id: "pq132", topic: "rhetoric", difficulty: "very_hard", question: "Argument: 'All winners had coaches. So a coach is necessary to win.' The flaw is:", options: [{ key: "A", text: "Uses one example." }, { key: "B", text: "Confuses necessary with sufficient." }, { key: "C", text: "Attacks the source." }, { key: "D", text: "Emotional appeal." }], correctKey: "B", explanation: "Having a coach in all winners doesn't prove necessity; confuses necessary with sufficient." },
  // Conventions advanced
  { id: "pq133", topic: "conventions-advanced", difficulty: "medium", question: "Which is correct? 'The results were clear ___ the experiment succeeded.'", options: [{ key: "A", text: "the experiment" }, { key: "B", text: "; the experiment" }, { key: "C", text: ", the experiment" }, { key: "D", text: "—the experiment" }], correctKey: "B", explanation: "Semicolon joins two independent clauses. Comma would be a splice." },
  { id: "pq134", topic: "conventions-advanced", difficulty: "hard", question: "Which revision fixes the modifier? 'Running to class, the book was left behind.'", options: [{ key: "A", text: "Running to class, the book was left behind." }, { key: "B", text: "Running to class, I left the book behind." }, { key: "C", text: "The book was left behind running to class." }, { key: "D", text: "Running to class the book was left behind." }], correctKey: "B", explanation: "The one running must be the subject—I left the book." },
  { id: "pq135", topic: "conventions-advanced", difficulty: "very_hard", question: "Standard idiom: 'interested ___ learning more.'", options: [{ key: "A", text: "about" }, { key: "B", text: "in" }, { key: "C", text: "to" }, { key: "D", text: "for" }], correctKey: "B", explanation: "Correct idiom is 'interested in.'" },
  // More very hard across topics
  { id: "pq136", topic: "algebra", difficulty: "very_hard", question: "If (x-1)(x-2)(x-3)=0 and x>2.5, then x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "C", explanation: "Roots 1, 2, 3; only 3 > 2.5." },
  { id: "pq137", topic: "quadratics", difficulty: "very_hard", question: "Vertex of y = x² - 6x + 11 is at:", options: [{ key: "A", text: "(3, 2)" }, { key: "B", text: "(3, -2)" }, { key: "C", text: "(-3, 2)" }, { key: "D", text: "(6, 11)" }], correctKey: "A", explanation: "x = 6/2 = 3; y = 9 - 18 + 11 = 2." },
  { id: "pq138", topic: "functions", difficulty: "very_hard", question: "If f(x)=2x-1 and f(g(x))=4x+1, then g(x)=?", options: [{ key: "A", text: "2x" }, { key: "B", text: "2x+1" }, { key: "C", text: "4x" }, { key: "D", text: "4x+2" }], correctKey: "B", explanation: "f(g)=2g-1=4x+1 → g=2x+1." },
  { id: "pq139", topic: "data", difficulty: "very_hard", question: "Five numbers, mean 12. One number is removed; new mean 11. Removed number was:", options: [{ key: "A", text: "11" }, { key: "B", text: "12" }, { key: "C", text: "16" }, { key: "D", text: "17" }], correctKey: "C", explanation: "Original sum = 60. After removal, 4 numbers have mean 11, so sum 44. Removed = 60 - 44 = 16." },
  { id: "pq140", topic: "geometry", difficulty: "very_hard", question: "Line y=2x+k is tangent to x²+y²=20. |k| = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "2√5" }, { key: "C", text: "√20" }, { key: "D", text: "10" }], correctKey: "D", explanation: "Substitute: x²+(2x+k)²=20 → 5x²+4kx+k²-20=0. Discriminant 0: 16k²-20(k²-20)=0 → -4k²+400=0 → k²=100 → |k|=10." },
  { id: "pq141", topic: "evidence", difficulty: "very_hard", question: "Best strategy for paired evidence: answer main question first, then choose lines that:", options: [{ key: "A", text: "Mention the topic" }, { key: "B", text: "Directly support that answer" }, { key: "C", text: "Are longest" }, { key: "D", text: "Appear in the first paragraph" }], correctKey: "B", explanation: "Evidence must directly support the answer you chose." },
  { id: "pq142", topic: "words", difficulty: "very_hard", question: "In 'her remarks were trenchant,' trenchant means:", options: [{ key: "A", text: "long" }, { key: "B", text: "sharp and incisive" }, { key: "C", text: "kind" }, { key: "D", text: "quiet" }], correctKey: "B", explanation: "Trenchant = sharp, cutting, incisive." },
  { id: "pq143", topic: "grammar", difficulty: "very_hard", question: "Which is correct? 'Neither the manager nor the employees ___ satisfied.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "was" }, { key: "D", text: "were" }], correctKey: "B", explanation: "With 'nor,' verb agrees with closer subject: 'employees' (plural) → are." },
  { id: "pq144", topic: "reading", difficulty: "very_hard", question: "'Every finalist completed the course.' What must be true?", options: [{ key: "A", text: "The course is required." }, { key: "B", text: "Everyone who took the course is a finalist." }, { key: "C", text: "At least one finalist completed the course." }, { key: "D", text: "No non-finalist completed it." }], correctKey: "C", explanation: "If every finalist completed it, then at least one finalist completed it." },
  { id: "pq145", topic: "transitions", difficulty: "very_hard", question: "Which signals that the following sentence will qualify the previous one?", options: [{ key: "A", text: "Furthermore" }, { key: "B", text: "However" }, { key: "C", text: "For example" }, { key: "D", text: "Similarly" }], correctKey: "B", explanation: "However introduces a contrast or qualification." },
  // More algebra – wide range
  { id: "pq146", topic: "algebra", difficulty: "easy", question: "If 9x - 4 = 23, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "9x = 27, so x = 3." },
  { id: "pq147", topic: "algebra", difficulty: "easy", question: "Simplify: 5 - 2(x + 1)", options: [{ key: "A", text: "3 - 2x" }, { key: "B", text: "7 - 2x" }, { key: "C", text: "3 + 2x" }, { key: "D", text: "4 - 2x" }], correctKey: "A", explanation: "5 - 2x - 2 = 3 - 2x." },
  { id: "pq148", topic: "algebra", difficulty: "medium", question: "If 2/x = 5, then x = ?", options: [{ key: "A", text: "2/5" }, { key: "B", text: "5/2" }, { key: "C", text: "10" }, { key: "D", text: "7" }], correctKey: "A", explanation: "2/x = 5 → x = 2/5." },
  { id: "pq149", topic: "algebra", difficulty: "medium", question: "If 5x - 2y = 16 and x + 2y = 8, what is x?", options: [{ key: "A", text: "2" }, { key: "B", text: "4" }, { key: "C", text: "6" }, { key: "D", text: "8" }], correctKey: "B", explanation: "Add: 6x = 24 → x = 4." },
  { id: "pq150", topic: "algebra", difficulty: "hard", question: "If x² - 5x + 6 = 0 and x > 2.5, what is x?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "6" }], correctKey: "B", explanation: "Factor: (x-2)(x-3)=0. Roots 2 and 3; only 3 > 2.5." },
  { id: "pq151", topic: "algebra", difficulty: "very_hard", question: "If |x - 3| = 5, then the sum of all possible x is:", options: [{ key: "A", text: "0" }, { key: "B", text: "5" }, { key: "C", text: "6" }, { key: "D", text: "10" }], correctKey: "C", explanation: "x - 3 = 5 → x = 8; x - 3 = -5 → x = -2. Sum = 6." },
  // Quadratics
  { id: "pq152", topic: "quadratics", difficulty: "easy", question: "What is the y-intercept of y = x² + 2x - 5?", options: [{ key: "A", text: "-5" }, { key: "B", text: "0" }, { key: "C", text: "2" }, { key: "D", text: "5" }], correctKey: "A", explanation: "Set x = 0: y = -5." },
  { id: "pq153", topic: "quadratics", difficulty: "medium", question: "For x² + kx + 9 = 0 to have one real root, k = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "6" }, { key: "C", text: "±6" }, { key: "D", text: "±3" }], correctKey: "C", explanation: "Discriminant k² - 36 = 0 → k = ±6." },
  { id: "pq154", topic: "quadratics", difficulty: "hard", question: "If the roots of x² - 8x + c = 0 are equal, then c = ?", options: [{ key: "A", text: "8" }, { key: "B", text: "12" }, { key: "C", text: "16" }, { key: "D", text: "64" }], correctKey: "C", explanation: "64 - 4c = 0 → c = 16." },
  { id: "pq155", topic: "quadratics", difficulty: "very_hard", question: "The parabola y = -2x² + 8x - 5 has its vertex at x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "4" }, { key: "D", text: "8" }], correctKey: "B", explanation: "Vertex x = -b/(2a) = -8/(-4) = 2." },
  // Functions
  { id: "pq156", topic: "functions", difficulty: "easy", question: "If f(x) = 4x, then f(3) = ?", options: [{ key: "A", text: "7" }, { key: "B", text: "12" }, { key: "C", text: "34" }, { key: "D", text: "81" }], correctKey: "B", explanation: "f(3) = 4(3) = 12." },
  { id: "pq157", topic: "functions", difficulty: "medium", question: "If f(x) = x² - 1 and g(x) = x + 1, then f(g(2)) = ?", options: [{ key: "A", text: "6" }, { key: "B", text: "8" }, { key: "C", text: "10" }, { key: "D", text: "12" }], correctKey: "B", explanation: "g(2)=3, f(3)=9-1=8." },
  { id: "pq158", topic: "functions", difficulty: "hard", question: "If f(x) = 1/(x+2), which x is NOT in the domain?", options: [{ key: "A", text: "-3" }, { key: "B", text: "-2" }, { key: "C", text: "0" }, { key: "D", text: "2" }], correctKey: "B", explanation: "x = -2 makes the denominator zero." },
  { id: "pq159", topic: "functions", difficulty: "very_hard", question: "If f(x) = 3x + 2 and f(k) = 14, then k = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "4" }, { key: "C", text: "6" }, { key: "D", text: "8" }], correctKey: "B", explanation: "3k + 2 = 14 → k = 4." },
  // Data
  { id: "pq160", topic: "data", difficulty: "easy", question: "What is the range of 3, 7, 2, 9, 5?", options: [{ key: "A", text: "4" }, { key: "B", text: "5" }, { key: "C", text: "7" }, { key: "D", text: "9" }], correctKey: "C", explanation: "Range = 9 - 2 = 7." },
  { id: "pq161", topic: "data", difficulty: "medium", question: "Five numbers have mean 6. Their sum is:", options: [{ key: "A", text: "6" }, { key: "B", text: "11" }, { key: "C", text: "30" }, { key: "D", text: "36" }], correctKey: "C", explanation: "Sum = mean × count = 6 × 5 = 30." },
  { id: "pq162", topic: "data", difficulty: "hard", question: "Median of 1, 3, 5, 7, 9, 11?", options: [{ key: "A", text: "5" }, { key: "B", text: "6" }, { key: "C", text: "7" }, { key: "D", text: "8" }], correctKey: "B", explanation: "Even count: median = average of 5 and 7 = 6." },
  { id: "pq163", topic: "data", difficulty: "very_hard", question: "If the mean of 4 numbers is 12 and three are 10, 12, 14, the fourth is:", options: [{ key: "A", text: "10" }, { key: "B", text: "12" }, { key: "C", text: "14" }, { key: "D", text: "16" }], correctKey: "B", explanation: "Sum = 48. Three sum to 36, so fourth = 12." },
  // Geometry
  { id: "pq164", topic: "geometry", difficulty: "easy", question: "Area of rectangle with length 8 and width 5?", options: [{ key: "A", text: "13" }, { key: "B", text: "26" }, { key: "C", text: "40" }, { key: "D", text: "80" }], correctKey: "C", explanation: "A = lw = 8(5) = 40." },
  { id: "pq165", topic: "geometry", difficulty: "medium", question: "A circle has area 64π. Its radius is:", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "8" }, { key: "D", text: "16" }], correctKey: "C", explanation: "πr² = 64π → r² = 64 → r = 8." },
  { id: "pq166", topic: "geometry", difficulty: "hard", question: "Two similar triangles have sides in ratio 2:5. If the smaller has area 12, the larger has area:", options: [{ key: "A", text: "30" }, { key: "B", text: "75" }, { key: "C", text: "120" }, { key: "D", text: "300" }], correctKey: "B", explanation: "Area ratio (2/5)² = 4/25. 12/large = 4/25 → large = 75." },
  { id: "pq167", topic: "geometry", difficulty: "very_hard", question: "A cone has radius 4 and height 6. Its volume is:", options: [{ key: "A", text: "24π" }, { key: "B", text: "32π" }, { key: "C", text: "48π" }, { key: "D", text: "96π" }], correctKey: "B", explanation: "V = (1/3)πr²h = (1/3)π(16)(6) = 32π." },
  // Inequalities
  { id: "pq168", topic: "inequalities", difficulty: "easy", question: "Solve: x + 7 > 15", options: [{ key: "A", text: "x > 7" }, { key: "B", text: "x > 8" }, { key: "C", text: "x < 8" }, { key: "D", text: "x > 22" }], correctKey: "B", explanation: "x > 8." },
  { id: "pq169", topic: "inequalities", difficulty: "medium", question: "Solve: 4 - 2x ≤ 10", options: [{ key: "A", text: "x ≤ -3" }, { key: "B", text: "x ≥ -3" }, { key: "C", text: "x ≤ 3" }, { key: "D", text: "x ≥ 3" }], correctKey: "B", explanation: "-2x ≤ 6; divide by -2, flip: x ≥ -3." },
  { id: "pq170", topic: "inequalities", difficulty: "hard", question: "Which x satisfies both x > 2 and x < 7?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "5" }, { key: "D", text: "8" }], correctKey: "C", explanation: "5 is in the interval (2, 7)." },
  { id: "pq171", topic: "inequalities", difficulty: "very_hard", question: "How many positive integers satisfy 2x + 1 < 10?", options: [{ key: "A", text: "3" }, { key: "B", text: "4" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "B", explanation: "2x < 9 → x < 4.5. Positive integers: 1, 2, 3, 4 → 4 values." },
  // Exponentials
  { id: "pq172", topic: "exponentials", difficulty: "easy", question: "If 5^x = 25, then x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "5" }, { key: "D", text: "25" }], correctKey: "B", explanation: "25 = 5², so x = 2." },
  { id: "pq173", topic: "exponentials", difficulty: "medium", question: "If 10^x = 1000, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "10" }], correctKey: "B", explanation: "1000 = 10³, so x = 3." },
  { id: "pq174", topic: "exponentials", difficulty: "hard", question: "A quantity halves every 4 years. After 12 years it is what fraction of the original?", options: [{ key: "A", text: "1/3" }, { key: "B", text: "1/6" }, { key: "C", text: "1/8" }, { key: "D", text: "1/12" }], correctKey: "C", explanation: "Halves 3 times: (1/2)³ = 1/8." },
  { id: "pq175", topic: "exponentials", difficulty: "very_hard", question: "If 2^(x+1) = 32, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "4" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "B", explanation: "32 = 2^5, so x+1 = 5, x = 4." },
  // Trigonometry
  { id: "pq176", topic: "trigonometry", difficulty: "easy", question: "In a right triangle, if one leg is 3 and hypotenuse is 5, the other leg is:", options: [{ key: "A", text: "2" }, { key: "B", text: "4" }, { key: "C", text: "√34" }, { key: "D", text: "8" }], correctKey: "B", explanation: "3² + b² = 5² → b² = 16 → b = 4." },
  { id: "pq177", topic: "trigonometry", difficulty: "medium", question: "In a 45-45-90 triangle with hypotenuse 6, each leg is:", options: [{ key: "A", text: "3" }, { key: "B", text: "3√2" }, { key: "C", text: "6" }, { key: "D", text: "6√2" }], correctKey: "B", explanation: "Leg = hyp/√2 = 6/√2 = 3√2." },
  { id: "pq178", topic: "trigonometry", difficulty: "hard", question: "Point (5, 0) is on a circle center (0,0) radius 5. Another point on the circle is:", options: [{ key: "A", text: "(0, 0)" }, { key: "B", text: "(0, 5)" }, { key: "C", text: "(3, 4)" }, { key: "D", text: "(5, 5)" }], correctKey: "B", explanation: "(0,5) has distance 5 from origin." },
  { id: "pq179", topic: "trigonometry", difficulty: "very_hard", question: "For 0° < θ < 90°, if cos θ = 1/2, then θ = ?", options: [{ key: "A", text: "30°" }, { key: "B", text: "45°" }, { key: "C", text: "60°" }, { key: "D", text: "90°" }], correctKey: "C", explanation: "cos 60° = 1/2." },
  // Word problems
  { id: "pq180", topic: "word-problems", difficulty: "easy", question: "A shirt costs $20 after a 20% discount. Original price was:", options: [{ key: "A", text: "$22" }, { key: "B", text: "$24" }, { key: "C", text: "$25" }, { key: "D", text: "$28" }], correctKey: "C", explanation: "0.80p = 20 → p = 25." },
  { id: "pq181", topic: "word-problems", difficulty: "medium", question: "Traveling 60 mph for 2.5 hours covers how many miles?", options: [{ key: "A", text: "120" }, { key: "B", text: "150" }, { key: "C", text: "180" }, { key: "D", text: "240" }], correctKey: "B", explanation: "60 × 2.5 = 150." },
  { id: "pq182", topic: "word-problems", difficulty: "hard", question: "Two numbers sum to 25 and differ by 5. The larger is:", options: [{ key: "A", text: "10" }, { key: "B", text: "15" }, { key: "C", text: "20" }, { key: "D", text: "25" }], correctKey: "B", explanation: "a+b=25, a-b=5 → 2a=30 → a=15." },
  { id: "pq183", topic: "word-problems", difficulty: "very_hard", question: "A is 50% more than B. B is what percent of A?", options: [{ key: "A", text: "50%" }, { key: "B", text: "66⅔%" }, { key: "C", text: "75%" }, { key: "D", text: "100%" }], correctKey: "B", explanation: "A = 1.5B, so B/A = 1/1.5 = 2/3 ≈ 66⅔%." },
  // Advanced math
  { id: "pq184", topic: "advanced-math", difficulty: "medium", question: "Simplify: (x² - 4)/(x - 2) for x ≠ 2", options: [{ key: "A", text: "x - 2" }, { key: "B", text: "x + 2" }, { key: "C", text: "x² + 2" }, { key: "D", text: "2" }], correctKey: "B", explanation: "Factor: (x-2)(x+2)/(x-2) = x+2." },
  { id: "pq185", topic: "advanced-math", difficulty: "hard", question: "If (x-1) is a factor of x³ + ax² - 4, then a = ?", options: [{ key: "A", text: "-5" }, { key: "B", text: "-3" }, { key: "C", text: "3" }, { key: "D", text: "5" }], correctKey: "C", explanation: "P(1)=1+a-4=0 → a=3." },
  { id: "pq186", topic: "advanced-math", difficulty: "very_hard", question: "Solve: √(x + 4) = 5", options: [{ key: "A", text: "1" }, { key: "B", text: "9" }, { key: "C", text: "21" }, { key: "D", text: "29" }], correctKey: "C", explanation: "x + 4 = 25 → x = 21." },
  // Evidence & Reading
  { id: "pq187", topic: "evidence", difficulty: "easy", question: "A quote that 'directly supports' an answer means it:", options: [{ key: "A", text: "Is on the same page" }, { key: "B", text: "Proves or shows that answer" }, { key: "C", text: "Is the longest sentence" }, { key: "D", text: "Uses difficult words" }], correctKey: "B", explanation: "Directly supports = proves or clearly shows." },
  { id: "pq188", topic: "evidence", difficulty: "medium", question: "When two answer choices seem to support your answer, pick the one that:", options: [{ key: "A", text: "Is longer" }, { key: "B", text: "Most directly proves it" }, { key: "C", text: "Appears first" }, { key: "D", text: "Uses a quote" }], correctKey: "B", explanation: "Choose the evidence that most directly proves your answer." },
  { id: "pq189", topic: "reading", difficulty: "easy", question: "An expository passage mainly:", options: [{ key: "A", text: "Tells a story" }, { key: "B", text: "Explains or informs" }, { key: "C", text: "Persuades" }, { key: "D", text: "Describes a character" }], correctKey: "B", explanation: "Expository = explains or informs." },
  { id: "pq190", topic: "reading", difficulty: "medium", question: "The 'purpose' of a passage is the author's:", options: [{ key: "A", text: "First sentence" }, { key: "B", text: "Main goal (inform, persuade, etc.)" }, { key: "C", text: "Conclusion only" }, { key: "D", text: "Title" }], correctKey: "B", explanation: "Purpose = author's main goal." },
  { id: "pq191", topic: "words", difficulty: "easy", question: "In 'a concise summary,' concise means:", options: [{ key: "A", text: "long" }, { key: "B", text: "brief and clear" }, { key: "C", text: "confusing" }, { key: "D", text: "detailed" }], correctKey: "B", explanation: "Concise = brief and to the point." },
  { id: "pq192", topic: "words", difficulty: "medium", question: "In 'his stance was unequivocal,' unequivocal means:", options: [{ key: "A", text: "unclear" }, { key: "B", text: "clear and definite" }, { key: "C", text: "hostile" }, { key: "D", text: "friendly" }], correctKey: "B", explanation: "Unequivocal = clear, leaving no doubt." },
  { id: "pq193", topic: "grammar", difficulty: "easy", question: "Which is correct? 'Each of the students ___ a book.'", options: [{ key: "A", text: "have" }, { key: "B", text: "has" }, { key: "C", text: "having" }, { key: "D", text: "had" }], correctKey: "B", explanation: "'Each' is singular → has." },
  { id: "pq194", topic: "grammar", difficulty: "medium", question: "Which is correct? 'The group ___ decided.'", options: [{ key: "A", text: "have" }, { key: "B", text: "has" }, { key: "C", text: "were" }, { key: "D", text: "are" }], correctKey: "B", explanation: "Collective noun 'group' is singular in US usage." },
  { id: "pq195", topic: "transitions", difficulty: "easy", question: "Which adds more information? 'It rained. ___, the game was canceled.'", options: [{ key: "A", text: "However" }, { key: "B", text: "Therefore" }, { key: "C", text: "For example" }, { key: "D", text: "Meanwhile" }], correctKey: "B", explanation: "Therefore shows cause-effect (rain → canceled)." },
  { id: "pq196", topic: "transitions", difficulty: "medium", question: "Which introduces an example? 'Many plants need light. ___, sunflowers turn toward the sun.'", options: [{ key: "A", text: "However" }, { key: "B", text: "For instance" }, { key: "C", text: "Therefore" }, { key: "D", text: "Nevertheless" }], correctKey: "B", explanation: "For instance introduces an example." },
  // Main idea, tone, rhetoric
  { id: "pq197", topic: "main-idea", difficulty: "easy", question: "The main idea is usually:", options: [{ key: "A", text: "In the first word" }, { key: "B", text: "The central point of the whole passage" }, { key: "C", text: "A single detail" }, { key: "D", text: "The title only" }], correctKey: "B", explanation: "Main idea = central point of the whole passage." },
  { id: "pq198", topic: "main-idea", difficulty: "medium", question: "A too-narrow main-idea answer often:", options: [{ key: "A", text: "Covers the whole passage" }, { key: "B", text: "Focuses on one paragraph or detail" }, { key: "C", text: "Is vague" }, { key: "D", text: "Restates the title" }], correctKey: "B", explanation: "Too narrow = one part, not the whole." },
  { id: "pq199", topic: "tone", difficulty: "easy", question: "Tone is the author's:", options: [{ key: "A", text: "Length of sentences" }, { key: "B", text: "Attitude toward the subject" }, { key: "C", text: "Use of commas" }, { key: "D", text: "Number of paragraphs" }], correctKey: "B", explanation: "Tone = author's attitude." },
  { id: "pq200", topic: "tone", difficulty: "medium", question: "Words like 'unfortunately' and 'regrettably' suggest a tone of:", options: [{ key: "A", text: "Joy" }, { key: "B", text: "Regret or disappointment" }, { key: "C", text: "Neutrality" }, { key: "D", text: "Excitement" }], correctKey: "B", explanation: "Regret/disappointment." },
  { id: "pq201", topic: "rhetoric", difficulty: "easy", question: "The author includes a statistic primarily to:", options: [{ key: "A", text: "Fill space" }, { key: "B", text: "Support or illustrate a point" }, { key: "C", text: "Contradict the main idea" }, { key: "D", text: "End the passage" }], correctKey: "B", explanation: "Statistics support or illustrate the argument." },
  { id: "pq202", topic: "rhetoric", difficulty: "medium", question: "A counterargument is presented so the author can:", options: [{ key: "A", text: "Ignore it" }, { key: "B", text: "Address or refute it" }, { key: "C", text: "Repeat it" }, { key: "D", text: "Change the topic" }], correctKey: "B", explanation: "Counterarguments are raised to address or refute them." },
  { id: "pq203", topic: "conventions-advanced", difficulty: "easy", question: "A comma splice is:", options: [{ key: "A", text: "Two independent clauses joined only by a comma" }, { key: "B", text: "A correct use of a comma" }, { key: "C", text: "A missing comma" }, { key: "D", text: "A comma after 'and'" }], correctKey: "A", explanation: "Comma splice = two full sentences with only a comma." },
  { id: "pq204", topic: "conventions-advanced", difficulty: "medium", question: "Which is correct? 'She wanted one thing: to succeed.'", options: [{ key: "A", text: "thing; to" }, { key: "B", text: "thing: to" }, { key: "C", text: "thing, to" }, { key: "D", text: "thing to" }], correctKey: "B", explanation: "Colon introduces the explanation after a complete clause." },
  // More mixed difficulties
  { id: "pq205", topic: "algebra", difficulty: "easy", question: "If 8 - x = 3, then x = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "6" }, { key: "C", text: "11" }, { key: "D", text: "24" }], correctKey: "A", explanation: "8 - 3 = 5." },
  { id: "pq206", topic: "algebra", difficulty: "medium", question: "If 2x + 3y = 13 and x = 2, then y = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "4 + 3y = 13 → 3y = 9 → y = 3." },
  { id: "pq207", topic: "quadratics", difficulty: "easy", question: "x² - 4 = 0 has solutions:", options: [{ key: "A", text: "2 only" }, { key: "B", text: "-2 only" }, { key: "C", text: "2 and -2" }, { key: "D", text: "4 and -4" }], correctKey: "C", explanation: "x² = 4 → x = ±2." },
  { id: "pq208", topic: "data", difficulty: "easy", question: "If 6 numbers have sum 54, their mean is:", options: [{ key: "A", text: "6" }, { key: "B", text: "9" }, { key: "C", text: "12" }, { key: "D", text: "54" }], correctKey: "B", explanation: "Mean = 54/6 = 9." },
  { id: "pq209", topic: "geometry", difficulty: "easy", question: "Perimeter of rectangle length 10, width 6?", options: [{ key: "A", text: "16" }, { key: "B", text: "32" }, { key: "C", text: "60" }, { key: "D", text: "120" }], correctKey: "B", explanation: "P = 2(10+6) = 32." },
  { id: "pq210", topic: "algebra", difficulty: "hard", question: "If √(x) = 6, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "12" }, { key: "C", text: "36" }, { key: "D", text: "72" }], correctKey: "C", explanation: "x = 6² = 36." },
  { id: "pq211", topic: "quadratics", difficulty: "hard", question: "Sum of roots of x² + 5x + 6 = 0?", options: [{ key: "A", text: "5" }, { key: "B", text: "-5" }, { key: "C", text: "6" }, { key: "D", text: "-6" }], correctKey: "B", explanation: "Sum = -b/a = -5." },
  { id: "pq212", topic: "functions", difficulty: "easy", question: "If f(x) = 7 - x, then f(2) = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "9" }, { key: "C", text: "14" }, { key: "D", text: "-5" }], correctKey: "A", explanation: "f(2) = 7 - 2 = 5." },
  { id: "pq213", topic: "evidence", difficulty: "hard", question: "Wrong evidence often:", options: [{ key: "A", text: "Directly proves your answer" }, { key: "B", text: "Seems related but doesn't prove it" }, { key: "C", text: "Is too short" }, { key: "D", text: "Comes from the right paragraph" }], correctKey: "B", explanation: "Wrong evidence sounds relevant but doesn't prove the answer." },
  { id: "pq214", topic: "words", difficulty: "hard", question: "In 'a pragmatic approach,' pragmatic means:", options: [{ key: "A", text: "theoretical" }, { key: "B", text: "practical" }, { key: "C", text: "idealistic" }, { key: "D", text: "confusing" }], correctKey: "B", explanation: "Pragmatic = practical, focused on what works." },
  { id: "pq215", topic: "grammar", difficulty: "hard", question: "Which is correct? 'The number of students ___ rising.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "were" }, { key: "D", text: "have been" }], correctKey: "A", explanation: "Subject is 'number' (singular) → is." },
  { id: "pq216", topic: "reading", difficulty: "hard", question: "An inference must be:", options: [{ key: "A", text: "Stated in the passage" }, { key: "B", text: "Supported by the passage" }, { key: "C", text: "The main idea" }, { key: "D", text: "In the first sentence" }], correctKey: "B", explanation: "Inferences must be supported by the text." },
  { id: "pq217", topic: "algebra", difficulty: "very_hard", question: "If 2^(2x) = 16, then x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "4" }, { key: "D", text: "8" }], correctKey: "B", explanation: "16 = 2^4, so 2x = 4, x = 2." },
  { id: "pq218", topic: "data", difficulty: "very_hard", question: "Seven numbers have mean 8. If one number is 20, the sum of the other six is:", options: [{ key: "A", text: "28" }, { key: "B", text: "36" }, { key: "C", text: "56" }, { key: "D", text: "76" }], correctKey: "B", explanation: "Total sum = 56. 56 - 20 = 36." },
  { id: "pq219", topic: "geometry", difficulty: "very_hard", question: "A sector of 60° in a circle of radius 6 has area:", options: [{ key: "A", text: "π" }, { key: "B", text: "6π" }, { key: "C", text: "12π" }, { key: "D", text: "36π" }], correctKey: "B", explanation: "(60/360)×π(36) = 6π." },
  { id: "pq220", topic: "transitions", difficulty: "very_hard", question: "Which indicates a result? 'He studied hard. ___, he passed.'", options: [{ key: "A", text: "However" }, { key: "B", text: "Moreover" }, { key: "C", text: "Therefore" }, { key: "D", text: "Although" }], correctKey: "C", explanation: "Therefore indicates the result (passing)." },
  // Adapted from SAT practice sources (AnalyzeMath / SAT-style) – wide range
  { id: "pq221", topic: "algebra", difficulty: "medium", question: "If y = kx + 2k where k is constant, and y = -14 when x = 5, what is x when y = -24?", options: [{ key: "A", text: "-10" }, { key: "B", text: "10" }, { key: "C", text: "4" }, { key: "D", text: "-2" }], correctKey: "B", explanation: "-14 = 5k + 2k = 7k → k = -2. Then -24 = -2x - 4 → x = 10." },
  { id: "pq222", topic: "algebra", difficulty: "hard", question: "If m and n are positive integers and 3^m = 9^(1/n), what is m × n?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "9" }], correctKey: "B", explanation: "9^(1/n) = 3^(2/n). So 3^m = 3^(2/n) → m = 2/n → mn = 2." },
  { id: "pq223", topic: "functions", difficulty: "hard", question: "If f(x+1) = 2x - 1, then f(2x) = ?", options: [{ key: "A", text: "4x - 1" }, { key: "B", text: "2x - 2" }, { key: "C", text: "4x - 4" }, { key: "D", text: "4x - 3" }], correctKey: "D", explanation: "f(s) = 2(s-1) - 1 = 2s - 3 when s = x+1. So f(2x) = 2(2x) - 3 = 4x - 3." },
  { id: "pq224", topic: "geometry", difficulty: "medium", question: "Which point lies inside the circle (x - 2)² + (y + 3)² = 4?", options: [{ key: "A", text: "(0, -3)" }, { key: "B", text: "(3, -2)" }, { key: "C", text: "(4, 1)" }, { key: "D", text: "(0, 0)" }], correctKey: "B", explanation: "Center (2,-3), radius 2. (3,-2) is distance √2 from center < 2, so inside." },
  { id: "pq225", topic: "geometry", difficulty: "hard", question: "A rectangular field's perimeter is 8 times its width. If its area is 48 m², what is its perimeter in meters?", options: [{ key: "A", text: "8" }, { key: "B", text: "16" }, { key: "C", text: "24" }, { key: "D", text: "32" }], correctKey: "D", explanation: "2l + 2w = 8w → l = 3w. Area lw = 3w² = 48 → w = 4, l = 12. Perimeter = 2(4+12) = 32." },
  { id: "pq226", topic: "data", difficulty: "medium", question: "The average of the first 4 numbers in a set is 21. The average of the last 2 numbers is 27. What is the average of all 6 numbers?", options: [{ key: "A", text: "20" }, { key: "B", text: "22" }, { key: "C", text: "23" }, { key: "D", text: "24" }], correctKey: "C", explanation: "(4×21 + 2×27)/6 = (84 + 54)/6 = 23." },
  { id: "pq227", topic: "data", difficulty: "hard", question: "In an arithmetic sequence, the 4th term is 6.5 and the 7th term is 11. What is the 20th term?", options: [{ key: "A", text: "28" }, { key: "B", text: "30" }, { key: "C", text: "30.5" }, { key: "D", text: "32" }], correctKey: "C", explanation: "a + 3d = 6.5, a + 6d = 11 → 3d = 4.5, d = 1.5, a = 2. a₂₀ = 2 + 19(1.5) = 30.5." },
  { id: "pq228", topic: "word-problems", difficulty: "medium", question: "After a 15% discount, a TV costs $680. What was its original price?", options: [{ key: "A", text: "$591" }, { key: "B", text: "$800" }, { key: "C", text: "$765" }, { key: "D", text: "$900" }], correctKey: "B", explanation: "0.85p = 680 → p = 680/0.85 = 800." },
  { id: "pq229", topic: "quadratics", difficulty: "hard", question: "For which value(s) of m does -2x² + mx = 2 have exactly one solution?", options: [{ key: "A", text: "0" }, { key: "B", text: "2 only" }, { key: "C", text: "-2 and 2" }, { key: "D", text: "-4 and 4" }], correctKey: "D", explanation: "Rewrite: -2x² + mx - 2 = 0. One solution when discriminant m² - 16 = 0 → m = ±4." },
  { id: "pq230", topic: "algebra", difficulty: "easy", question: "If 2/3 of a number equals 5/3, what is the number?", options: [{ key: "A", text: "5/2" }, { key: "B", text: "2" }, { key: "C", text: "5" }, { key: "D", text: "10/3" }], correctKey: "A", explanation: "(2/3)n = 5/3 → n = 5/2." },
  { id: "pq231", topic: "algebra", difficulty: "medium", question: "If x + 2y + 3z = 20 and 3x + 2y - z = 10, and z = 0, what is 5x + 4y?", options: [{ key: "A", text: "20" }, { key: "B", text: "25" }, { key: "C", text: "30" }, { key: "D", text: "35" }], correctKey: "B", explanation: "With z=0: x+2y=20 and 3x+2y=10. Subtract: -2x=10, x=-5. Then 2y=25, so 4y=50. So 5x+4y = -25+50 = 25." },
  { id: "pq232", topic: "word-problems", difficulty: "hard", question: "Pedro drove 1.5 hours at 60 km/h and 3 hours at 70 km/h. What was his average speed in km/h?", options: [{ key: "A", text: "65" }, { key: "B", text: "66" }, { key: "C", text: "66.7" }, { key: "D", text: "70" }], correctKey: "C", explanation: "Distance: 1.5(60)+3(70)=90+210=300 km. Time: 4.5 hr. Average = 300/4.5 ≈ 66.7 km/h." },
  { id: "pq233", topic: "advanced-math", difficulty: "medium", question: "The expression √(x² + 2x + 1) equals which of the following?", options: [{ key: "A", text: "x + 1" }, { key: "B", text: "|x + 1|" }, { key: "C", text: "x - 1" }, { key: "D", text: "|x - 1|" }], correctKey: "B", explanation: "x²+2x+1 = (x+1)², so √((x+1)²) = |x+1|." },
  { id: "pq234", topic: "advanced-math", difficulty: "hard", question: "For all x, |−x² − 1| = ?", options: [{ key: "A", text: "x² − 1" }, { key: "B", text: "x² + 1" }, { key: "C", text: "-x² + 1" }, { key: "D", text: "-x² - 1" }], correctKey: "B", explanation: "−x² − 1 is always ≤ -1, so its absolute value is x² + 1." },
  { id: "pq235", topic: "quadratics", difficulty: "very_hard", question: "Twice the difference of the squares of two consecutive positive integers is 4n. What is their sum?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "2n" }, { key: "D", text: "4n" }], correctKey: "C", explanation: "Consecutive: k and k+1. 2((k+1)² - k²) = 4n → 2(2k+1) = 4n → 2k+1 = 2n. Their sum = k+(k+1) = 2k+1 = 2n." },
  { id: "pq236", topic: "evidence", difficulty: "easy", question: "When the question asks which quote 'best supports' your previous answer, you should choose the line that:", options: [{ key: "A", text: "Is the longest" }, { key: "B", text: "Directly proves or shows that answer" }, { key: "C", text: "Appears first in the passage" }, { key: "D", text: "Uses a statistic" }], correctKey: "B", explanation: "Best support = directly proves or shows your answer." },
  { id: "pq237", topic: "reading", difficulty: "medium", question: "When asked what the author 'would most likely agree with,' you should choose the answer that:", options: [{ key: "A", text: "Contradicts the passage" }, { key: "B", text: "Is consistent with the passage's main point and tone" }, { key: "C", text: "Is stated in the first sentence only" }, { key: "D", text: "Is the most extreme option" }], correctKey: "B", explanation: "Author would agree with what matches the passage's view." },
  { id: "pq238", topic: "words", difficulty: "medium", question: "In 'a superficial analysis,' superficial means:", options: [{ key: "A", text: "deep" }, { key: "B", text: "surface-level or shallow" }, { key: "C", text: "excellent" }, { key: "D", text: "lengthy" }], correctKey: "B", explanation: "Superficial = on the surface, not deep." },
  { id: "pq239", topic: "grammar", difficulty: "easy", question: "Which is correct? 'One of the students ___ late.'", options: [{ key: "A", text: "were" }, { key: "B", text: "was" }, { key: "C", text: "have been" }, { key: "D", text: "are" }], correctKey: "B", explanation: "'One' is the subject (singular) → was." },
  { id: "pq240", topic: "transitions", difficulty: "medium", question: "Which word signals that the next sentence will give an example? 'Stress affects health. ___, shift workers often have higher blood pressure.'", options: [{ key: "A", text: "However" }, { key: "B", text: "For example" }, { key: "C", text: "Therefore" }, { key: "D", text: "Similarly" }], correctKey: "B", explanation: "For example introduces an illustration." },
  // More from online SAT-style sources
  { id: "pq241", topic: "algebra", difficulty: "easy", question: "If 0.2x = 4, then x = ?", options: [{ key: "A", text: "8" }, { key: "B", text: "20" }, { key: "C", text: "0.8" }, { key: "D", text: "2" }], correctKey: "B", explanation: "x = 4/0.2 = 20." },
  { id: "pq242", topic: "quadratics", difficulty: "easy", question: "The product of the roots of x² - 7x + 12 = 0 is:", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "12" }, { key: "D", text: "19" }], correctKey: "C", explanation: "Product of roots = c/a = 12." },
  { id: "pq243", topic: "functions", difficulty: "medium", question: "If f(x) = x² - 4 and g(x) = x + 2, then f(g(x)) = ?", options: [{ key: "A", text: "x² - 2" }, { key: "B", text: "x² + 4x" }, { key: "C", text: "x² + 4x + 4" }, { key: "D", text: "x² + 4" }], correctKey: "B", explanation: "g(x)=x+2, f(g(x))=(x+2)²-4=x²+4x+4-4=x²+4x." },
  { id: "pq244", topic: "data", difficulty: "easy", question: "If 20% of 80 is x, then x = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "16" }, { key: "C", text: "20" }, { key: "D", text: "60" }], correctKey: "B", explanation: "0.20 × 80 = 16." },
  { id: "pq245", topic: "geometry", difficulty: "easy", question: "How many degrees are in 3/4 of a full rotation?", options: [{ key: "A", text: "90" }, { key: "B", text: "180" }, { key: "C", text: "270" }, { key: "D", text: "360" }], correctKey: "C", explanation: "(3/4)(360) = 270." },
  { id: "pq246", topic: "inequalities", difficulty: "medium", question: "If 5 - 3x > 14, then x < ?", options: [{ key: "A", text: "-3" }, { key: "B", text: "3" }, { key: "C", text: "-3 and flip" }, { key: "D", text: "-19/3" }], correctKey: "A", explanation: "-3x > 9 → x < -3 (flip when dividing by negative)." },
  { id: "pq247", topic: "exponentials", difficulty: "easy", question: "If 4^x = 64, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "16" }], correctKey: "B", explanation: "64 = 4³, so x = 3." },
  { id: "pq248", topic: "trigonometry", difficulty: "medium", question: "In a right triangle, if the hypotenuse is 10 and one leg is 6, the other leg is:", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "8" }, { key: "D", text: "12" }], correctKey: "C", explanation: "6² + b² = 10² → b² = 64 → b = 8." },
  { id: "pq249", topic: "main-idea", difficulty: "hard", question: "A passage describes a scientist's experiment and its unexpected result. The main idea is best stated as:", options: [{ key: "A", text: "The scientist worked in a lab." }, { key: "B", text: "An experiment yielded an unexpected result." }, { key: "C", text: "Science is important." }, { key: "D", text: "The result was expected." }], correctKey: "B", explanation: "Main idea = central point: experiment and its unexpected result." },
  { id: "pq250", topic: "rhetoric", difficulty: "hard", question: "The author cites a study showing 80% success. This citation primarily:", options: [{ key: "A", text: "Fills space" }, { key: "B", text: "Supports the author's claim with data" }, { key: "C", text: "Contradicts the main idea" }, { key: "D", text: "Introduces a new topic" }], correctKey: "B", explanation: "Citations typically support the author's claim with evidence." },
];

const MATH_TOPICS = ["algebra", "quadratics", "functions", "data", "geometry", "inequalities", "exponentials", "trigonometry", "word-problems", "advanced-math"];
const READING_TOPICS = ["evidence", "words", "reading", "grammar", "transitions", "main-idea", "tone", "rhetoric", "conventions-advanced"];

export function getQuestionsByTopic(topic: string): PracticeBankQuestion[] {
  if (topic === "math") return PRACTICE_QUESTIONS.filter((q) => MATH_TOPICS.includes(q.topic));
  if (topic === "reading") return PRACTICE_QUESTIONS.filter((q) => READING_TOPICS.includes(q.topic));
  return PRACTICE_QUESTIONS.filter((q) => q.topic === topic);
}

const DIFF_ORDER = { easy: 0, medium: 1, hard: 2, very_hard: 3 };

/** Returns questions ordered by difficulty (easy → medium → hard → very_hard), filtered by topic and optional difficulty */
export function getQuestionsByDifficultyOrdered(
  count: number,
  topic?: string,
  difficulty?: "easy" | "medium" | "hard" | "very_hard"
): PracticeBankQuestion[] {
  let pool = topic ? getQuestionsByTopic(topic) : [...PRACTICE_QUESTIONS];
  if (difficulty) {
    pool = pool.filter((q) => q.difficulty === difficulty);
  }
  const sorted = pool.sort((a, b) => DIFF_ORDER[a.difficulty] - DIFF_ORDER[b.difficulty]);
  return sorted.slice(0, Math.min(count, sorted.length));
}

export function getRandomQuestions(count: number, topic?: string): PracticeBankQuestion[] {
  let pool = topic ? getQuestionsByTopic(topic) : [...PRACTICE_QUESTIONS];
  const shuffled = pool.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
