import type { PracticeQuestion } from "./lessons";

export interface PracticeBankQuestion extends PracticeQuestion {
  topic: string;
  difficulty: "easy" | "medium" | "hard";
}

export const PRACTICE_QUESTIONS: PracticeBankQuestion[] = [
  // Math - Algebra
  { id: "pq1", topic: "algebra", difficulty: "easy", question: "Solve: 5x - 3 = 12", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "5x = 15, so x = 3." },
  { id: "pq2", topic: "algebra", difficulty: "easy", question: "If 2(x + 4) = 18, then x = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "6" }, { key: "C", text: "7" }, { key: "D", text: "8" }], correctKey: "A", explanation: "2x + 8 = 18 → 2x = 10 → x = 5." },
  { id: "pq3", topic: "algebra", difficulty: "medium", question: "For what value of k does 3x + ky = 6 have slope -2?", options: [{ key: "A", text: "-6" }, { key: "B", text: "-3/2" }, { key: "C", text: "3/2" }, { key: "D", text: "6" }], correctKey: "C", explanation: "Slope = -3/k = -2, so k = 3/2." },
  { id: "pq4", topic: "algebra", difficulty: "medium", question: "If x² = 49, what is |x|?", options: [{ key: "A", text: "7" }, { key: "B", text: "49" }, { key: "C", text: "±7" }, { key: "D", text: "7 or -7" }], correctKey: "A", explanation: "|x| is the absolute value, so |7| = |-7| = 7." },
  { id: "pq5", topic: "algebra", difficulty: "hard", question: "If a + b = 10 and ab = 21, what is a² + b²?", options: [{ key: "A", text: "58" }, { key: "B", text: "79" }, { key: "C", text: "100" }, { key: "D", text: "121" }], correctKey: "A", explanation: "(a+b)² = a²+2ab+b². So 100 = a²+b²+42, hence a²+b² = 58." },
  // Math - Quadratics
  { id: "pq6", topic: "quadratics", difficulty: "easy", question: "What are the roots of x² - 9 = 0?", options: [{ key: "A", text: "3 only" }, { key: "B", text: "-3 only" }, { key: "C", text: "3 and -3" }, { key: "D", text: "9 and -9" }], correctKey: "C", explanation: "x² = 9 → x = ±3." },
  { id: "pq7", topic: "quadratics", difficulty: "medium", question: "The vertex of y = x² - 4x + 3 is at x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "B", explanation: "Vertex x = -b/(2a) = 4/2 = 2." },
  { id: "pq8", topic: "quadratics", difficulty: "hard", question: "For x² - 6x + c = 0 to have one real root, c = ?", options: [{ key: "A", text: "6" }, { key: "B", text: "9" }, { key: "C", text: "12" }, { key: "D", text: "18" }], correctKey: "B", explanation: "Discriminant b²-4ac = 0: 36-4c = 0, so c = 9." },
  // Math - Functions
  { id: "pq9", topic: "functions", difficulty: "easy", question: "If f(x) = x² + 1, then f(-2) = ?", options: [{ key: "A", text: "-3" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "7" }], correctKey: "C", explanation: "f(-2) = (-2)² + 1 = 4 + 1 = 5." },
  { id: "pq10", topic: "functions", difficulty: "medium", question: "If f(x) = 2x - 1 and g(x) = x + 3, what is f(g(2))?", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "9" }, { key: "D", text: "11" }], correctKey: "C", explanation: "g(2)=5, f(5)=2(5)-1=9." },
  // Math - Data
  { id: "pq11", topic: "data", difficulty: "easy", question: "Mean of 4, 6, 8, 10?", options: [{ key: "A", text: "6" }, { key: "B", text: "7" }, { key: "C", text: "8" }, { key: "D", text: "9" }], correctKey: "B", explanation: "(4+6+8+10)/4 = 28/4 = 7." },
  { id: "pq12", topic: "data", difficulty: "medium", question: "Data: 2, 4, 6, 6, 10. What is the mode?", options: [{ key: "A", text: "4" }, { key: "B", text: "5.6" }, { key: "C", text: "6" }, { key: "D", text: "10" }], correctKey: "C", explanation: "Mode is the most frequent value: 6." },
  // Math - Geometry
  { id: "pq13", topic: "geometry", difficulty: "easy", question: "Area of a circle with radius 5?", options: [{ key: "A", text: "10π" }, { key: "B", text: "25π" }, { key: "C", text: "50π" }, { key: "D", text: "100π" }], correctKey: "B", explanation: "A = πr² = π(25) = 25π." },
  { id: "pq14", topic: "geometry", difficulty: "medium", question: "A 30-60-90 triangle has short leg 4. What is the hypotenuse?", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "8" }, { key: "D", text: "12" }], correctKey: "C", explanation: "Hypotenuse = 2 × short leg = 8." },
  // Reading - Evidence
  { id: "pq15", topic: "evidence", difficulty: "easy", question: "The best evidence for an answer typically:", options: [{ key: "A", text: "Restates the question" }, { key: "B", text: "Directly supports the claim" }, { key: "C", text: "Is the longest sentence" }, { key: "D", text: "Uses emotional language" }], correctKey: "B", explanation: "Evidence must directly support your answer choice." },
  { id: "pq16", topic: "evidence", difficulty: "medium", question: "Paired evidence questions on the SAT often:", options: [{ key: "A", text: "Have no wrong answers" }, { key: "B", text: "Link back to your previous answer" }, { key: "C", text: "Require outside knowledge" }, { key: "D", text: "Test vocabulary only" }], correctKey: "B", explanation: "Evidence must support the answer you chose in the prior question." },
  // Reading - Words in Context
  { id: "pq17", topic: "words", difficulty: "easy", question: "In 'a fleeting moment,' fleeting means:", options: [{ key: "A", text: "lasting" }, { key: "B", text: "brief" }, { key: "C", text: "bright" }, { key: "D", text: "slow" }], correctKey: "B", explanation: "Fleeting means short-lived or brief." },
  { id: "pq18", topic: "words", difficulty: "medium", question: "In 'her words were equivocal,' equivocal means:", options: [{ key: "A", text: "clear" }, { key: "B", text: "ambiguous" }, { key: "C", text: "harsh" }, { key: "D", text: "kind" }], correctKey: "B", explanation: "Equivocal means ambiguous or open to multiple interpretations." },
  // Grammar
  { id: "pq19", topic: "grammar", difficulty: "easy", question: "Which is correct? 'Neither John nor his friends ___ going.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "was" }, { key: "D", text: "were" }], correctKey: "B", explanation: "With 'nor,' the verb agrees with the closer subject: 'friends' is plural, so 'are.'" },
  { id: "pq20", topic: "grammar", difficulty: "medium", question: "Which fixes the run-on? 'She ran fast she won the race.'", options: [{ key: "A", text: "She ran fast, she won the race." }, { key: "B", text: "She ran fast; she won the race." }, { key: "C", text: "She ran fast and she won the race." }, { key: "D", text: "Both B and C" }], correctKey: "D", explanation: "Semicolon or conjunction both fix the run-on." },
  // More Math
  { id: "pq21", topic: "algebra", difficulty: "easy", question: "Simplify: 3(x - 4) + 2x", options: [{ key: "A", text: "5x - 12" }, { key: "B", text: "5x - 4" }, { key: "C", text: "6x - 12" }, { key: "D", text: "6x - 4" }], correctKey: "A", explanation: "3x - 12 + 2x = 5x - 12." },
  { id: "pq22", topic: "algebra", difficulty: "medium", question: "If 2^x = 8, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "8" }], correctKey: "B", explanation: "8 = 2³, so x = 3." },
  { id: "pq23", topic: "algebra", difficulty: "medium", question: "Solve |2x - 4| = 10", options: [{ key: "A", text: "x = 7 only" }, { key: "B", text: "x = -3 only" }, { key: "C", text: "x = 7 or x = -3" }, { key: "D", text: "No solution" }], correctKey: "C", explanation: "2x-4=10 → x=7; 2x-4=-10 → x=-3." },
  { id: "pq24", topic: "quadratics", difficulty: "easy", question: "(x + 5)(x - 5) = ?", options: [{ key: "A", text: "x² - 25" }, { key: "B", text: "x² + 25" }, { key: "C", text: "x² - 10" }, { key: "D", text: "x² + 10x - 25" }], correctKey: "A", explanation: "Difference of squares: (x+5)(x-5) = x² - 25." },
  { id: "pq25", topic: "quadratics", difficulty: "hard", question: "For x² + bx + 16 to be a perfect square, b = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "8" }, { key: "C", text: "±8" }, { key: "D", text: "±4" }], correctKey: "C", explanation: "(x±4)² = x² ± 8x + 16, so b = ±8." },
  { id: "pq26", topic: "geometry", difficulty: "easy", question: "Perimeter of a square with side 7?", options: [{ key: "A", text: "14" }, { key: "B", text: "28" }, { key: "C", text: "49" }, { key: "D", text: "56" }], correctKey: "B", explanation: "P = 4s = 4(7) = 28." },
  { id: "pq27", topic: "geometry", difficulty: "medium", question: "Volume of a cylinder with r=3, h=4?", options: [{ key: "A", text: "12π" }, { key: "B", text: "24π" }, { key: "C", text: "36π" }, { key: "D", text: "48π" }], correctKey: "C", explanation: "V = πr²h = π(9)(4) = 36π." },
  { id: "pq28", topic: "data", difficulty: "hard", question: "If the mean of 5 numbers is 20 and four are 15, 20, 25, 20, the fifth is:", options: [{ key: "A", text: "15" }, { key: "B", text: "20" }, { key: "C", text: "25" }, { key: "D", text: "30" }], correctKey: "B", explanation: "Sum = 100, four sum to 80, so fifth = 20." },
  { id: "pq29", topic: "reading", difficulty: "medium", question: "The main purpose of an argumentative passage is to:", options: [{ key: "A", text: "Entertain" }, { key: "B", text: "Persuade" }, { key: "C", text: "Describe" }, { key: "D", text: "Narrate" }], correctKey: "B", explanation: "Argumentative writing aims to persuade." },
  { id: "pq30", topic: "transitions", difficulty: "easy", question: "Which shows addition? The experiment failed. ___, we learned from it.", options: [{ key: "A", text: "However" }, { key: "B", text: "Therefore" }, { key: "C", text: "Moreover" }, { key: "D", text: "Consequently" }], correctKey: "C", explanation: "Moreover adds related information." },
  // Algebra - more
  { id: "pq31", topic: "algebra", difficulty: "easy", question: "Solve: 4x + 2 = 14", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "4x = 12, so x = 3." },
  { id: "pq32", topic: "algebra", difficulty: "easy", question: "If 3x - 5 = 16, then x = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "6" }, { key: "C", text: "7" }, { key: "D", text: "8" }], correctKey: "C", explanation: "3x = 21, so x = 7." },
  { id: "pq33", topic: "algebra", difficulty: "easy", question: "Simplify: 2(x + 3) - 4x", options: [{ key: "A", text: "-2x + 6" }, { key: "B", text: "-2x + 3" }, { key: "C", text: "2x + 6" }, { key: "D", text: "6x + 6" }], correctKey: "A", explanation: "2x + 6 - 4x = -2x + 6." },
  { id: "pq34", topic: "algebra", difficulty: "medium", question: "If x/4 + x/3 = 7, then x = ?", options: [{ key: "A", text: "10" }, { key: "B", text: "12" }, { key: "C", text: "14" }, { key: "D", text: "16" }], correctKey: "B", explanation: "LCD 12: 3x + 4x = 84, so x = 12." },
  { id: "pq35", topic: "algebra", difficulty: "medium", question: "If 3^(x+1) = 81, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "81 = 3^4, so x+1 = 4, x = 3." },
  { id: "pq36", topic: "algebra", difficulty: "medium", question: "If 2x + y = 7 and x - y = 2, what is x?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "C", explanation: "Add equations: 3x = 9, so x = 3." },
  { id: "pq37", topic: "algebra", difficulty: "hard", question: "If (x-2)(x-3) = 0 and x > 2.5, what is x?", options: [{ key: "A", text: "2" }, { key: "B", text: "2.5" }, { key: "C", text: "3" }, { key: "D", text: "5" }], correctKey: "C", explanation: "Roots are 2 and 3; x > 2.5 so x = 3." },
  // Algebra continued
  { id: "pq38", topic: "algebra", difficulty: "easy", question: "Solve: x/2 = 9", options: [{ key: "A", text: "4.5" }, { key: "B", text: "7" }, { key: "C", text: "18" }, { key: "D", text: "11" }], correctKey: "C", explanation: "x = 9 × 2 = 18." },
  { id: "pq39", topic: "algebra", difficulty: "medium", question: "If √(x+1) = 4, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "15" }, { key: "C", text: "16" }, { key: "D", text: "17" }], correctKey: "B", explanation: "x+1 = 16, so x = 15." },
  { id: "pq40", topic: "algebra", difficulty: "hard", question: "If 2^x · 2^3 = 2^8, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "5" }, { key: "C", text: "8" }, { key: "D", text: "11" }], correctKey: "B", explanation: "2^(x+3) = 2^8, so x+3 = 8, x = 5." },
  // Quadratics
  { id: "pq41", topic: "quadratics", difficulty: "easy", question: "Factor: x² + 5x + 6", options: [{ key: "A", text: "(x+1)(x+6)" }, { key: "B", text: "(x+2)(x+3)" }, { key: "C", text: "(x+2)(x+4)" }, { key: "D", text: "(x+1)(x+5)" }], correctKey: "B", explanation: "x²+5x+6 = (x+2)(x+3)." },
  { id: "pq42", topic: "quadratics", difficulty: "medium", question: "What is the y-intercept of y = x² - 4x + 3?", options: [{ key: "A", text: "-4" }, { key: "B", text: "0" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "C", explanation: "y-intercept: set x=0, y = 3." },
  { id: "pq43", topic: "quadratics", difficulty: "hard", question: "The sum of the roots of x² - 7x + 12 = 0 is:", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "12" }, { key: "D", text: "19" }], correctKey: "B", explanation: "Sum of roots = -b/a = 7." },
  // Functions
  { id: "pq44", topic: "functions", difficulty: "easy", question: "If g(x) = x - 4, then g(10) = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "10" }, { key: "D", text: "14" }], correctKey: "B", explanation: "g(10) = 10 - 4 = 6." },
  { id: "pq45", topic: "functions", difficulty: "medium", question: "If f(x) = x² and g(x) = x + 1, then f(g(2)) = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "9" }, { key: "C", text: "10" }, { key: "D", text: "12" }], correctKey: "B", explanation: "g(2)=3, f(3)=9." },
  { id: "pq46", topic: "functions", difficulty: "hard", question: "If f(x) = 2x - 1, what is f⁻¹(5)?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "Solve 2x-1=5 → x=3." },
  // Data
  { id: "pq47", topic: "data", difficulty: "easy", question: "Median of 1, 3, 5, 7, 9?", options: [{ key: "A", text: "3" }, { key: "B", text: "5" }, { key: "C", text: "7" }, { key: "D", text: "25" }], correctKey: "B", explanation: "Middle value is 5." },
  { id: "pq48", topic: "data", difficulty: "medium", question: "Range of 2, 5, 8, 11, 14?", options: [{ key: "A", text: "6" }, { key: "B", text: "8" }, { key: "C", text: "12" }, { key: "D", text: "14" }], correctKey: "C", explanation: "Range = max - min = 14 - 2 = 12." },
  { id: "pq49", topic: "data", difficulty: "hard", question: "If mean of 6 numbers is 10 and five are 8, 9, 10, 11, 12, the sixth is:", options: [{ key: "A", text: "8" }, { key: "B", text: "10" }, { key: "C", text: "12" }, { key: "D", text: "14" }], correctKey: "B", explanation: "Sum=60, five sum to 50, so sixth = 10." },
  // Geometry
  { id: "pq50", topic: "geometry", difficulty: "easy", question: "Circumference of circle with radius 10?", options: [{ key: "A", text: "10π" }, { key: "B", text: "20π" }, { key: "C", text: "100π" }, { key: "D", text: "200π" }], correctKey: "B", explanation: "C = 2πr = 20π." },
  { id: "pq51", topic: "geometry", difficulty: "medium", question: "A 45-45-90 triangle has leg 5. Hypotenuse = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "5√2" }, { key: "C", text: "10" }, { key: "D", text: "25" }], correctKey: "B", explanation: "Hypotenuse = leg × √2 = 5√2." },
  { id: "pq52", topic: "geometry", difficulty: "hard", question: "Volume of a sphere with radius 3?", options: [{ key: "A", text: "9π" }, { key: "B", text: "12π" }, { key: "C", text: "36π" }, { key: "D", text: "108π" }], correctKey: "C", explanation: "V = (4/3)πr³ = (4/3)π(27) = 36π." },
  // Reading & Grammar
  { id: "pq53", topic: "evidence", difficulty: "easy", question: "Evidence questions ask you to:", options: [{ key: "A", text: "Guess the author's intent" }, { key: "B", text: "Find text that supports your answer" }, { key: "C", text: "Summarize the passage" }, { key: "D", text: "Identify the main idea" }], correctKey: "B", explanation: "Evidence must support your prior answer." },
  { id: "pq54", topic: "words", difficulty: "easy", question: "In 'a tenuous connection,' tenuous means:", options: [{ key: "A", text: "strong" }, { key: "B", text: "weak" }, { key: "C", text: "obvious" }, { key: "D", text: "permanent" }], correctKey: "B", explanation: "Tenuous means weak or insubstantial." },
  { id: "pq55", topic: "grammar", difficulty: "easy", question: "Which is correct? 'The team ___ playing well.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "were" }, { key: "D", text: "been" }], correctKey: "A", explanation: "Collective noun 'team' is singular in US English." },
  { id: "pq56", topic: "grammar", difficulty: "medium", question: "Which fixes the comma splice? 'I ran, I was late.'", options: [{ key: "A", text: "I ran, I was late." }, { key: "B", text: "I ran; I was late." }, { key: "C", text: "I ran I was late." }, { key: "D", text: "I ran, because I was late." }], correctKey: "B", explanation: "Semicolon joins two independent clauses." },
  { id: "pq57", topic: "transitions", difficulty: "medium", question: "Which shows contrast? 'It rained. ___, the game continued.'", options: [{ key: "A", text: "Therefore" }, { key: "B", text: "Moreover" }, { key: "C", text: "Nevertheless" }, { key: "D", text: "Consequently" }], correctKey: "C", explanation: "Nevertheless shows contrast." },
  // More algebra
  { id: "pq58", topic: "algebra", difficulty: "easy", question: "If 6x = 18, then x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "12" }, { key: "D", text: "24" }], correctKey: "B", explanation: "x = 18/6 = 3." },
  { id: "pq59", topic: "algebra", difficulty: "easy", question: "Simplify: -2(x - 3) + 4", options: [{ key: "A", text: "-2x + 10" }, { key: "B", text: "-2x - 2" }, { key: "C", text: "-2x + 2" }, { key: "D", text: "2x + 10" }], correctKey: "A", explanation: "-2x + 6 + 4 = -2x + 10." },
  { id: "pq60", topic: "algebra", difficulty: "medium", question: "If 1/x + 1/2 = 1, then x = ?", options: [{ key: "A", text: "1" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "4" }], correctKey: "B", explanation: "1/x = 1/2, so x = 2." },
  { id: "pq61", topic: "algebra", difficulty: "hard", question: "If x + 1/x = 3, then x² + 1/x² = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "9" }, { key: "D", text: "11" }], correctKey: "B", explanation: "(x+1/x)² = x²+2+1/x² = 9, so x²+1/x² = 7." },
  // More quadratics
  { id: "pq62", topic: "quadratics", difficulty: "easy", question: "x² - 16 = 0 has solutions:", options: [{ key: "A", text: "4 only" }, { key: "B", text: "-4 only" }, { key: "C", text: "4 and -4" }, { key: "D", text: "8 and -8" }], correctKey: "C", explanation: "x² = 16 → x = ±4." },
  { id: "pq63", topic: "quadratics", difficulty: "medium", question: "Product of roots of x² - 5x + 6 = 0?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "D", explanation: "Product = c/a = 6." },
  { id: "pq64", topic: "quadratics", difficulty: "hard", question: "For x² + px + 9 = 0 to have one real root, |p| = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "6" }, { key: "C", text: "9" }, { key: "D", text: "12" }], correctKey: "B", explanation: "Discriminant = p² - 36 = 0, so p = ±6." },
  // More functions
  { id: "pq65", topic: "functions", difficulty: "easy", question: "If h(x) = 3x + 2, then h(0) = ?", options: [{ key: "A", text: "0" }, { key: "B", text: "2" }, { key: "C", text: "3" }, { key: "D", text: "5" }], correctKey: "B", explanation: "h(0) = 3(0) + 2 = 2." },
  { id: "pq66", topic: "functions", difficulty: "medium", question: "If f(x) = x + 1 and f(a) = 5, then a = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "4" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "B", explanation: "a + 1 = 5, so a = 4." },
  { id: "pq67", topic: "functions", difficulty: "hard", question: "If f(x) = 2x² - 3, then f(-1) = ?", options: [{ key: "A", text: "-5" }, { key: "B", text: "-1" }, { key: "C", text: "1" }, { key: "D", text: "5" }], correctKey: "B", explanation: "f(-1) = 2(1) - 3 = -1." },
  // More data
  { id: "pq68", topic: "data", difficulty: "easy", question: "Mode of 1, 2, 2, 3, 3, 3, 4?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "2.5" }, { key: "D", text: "4" }], correctKey: "B", explanation: "3 appears most often." },
  { id: "pq69", topic: "data", difficulty: "medium", question: "If 5 numbers have mean 8 and sum 40, how many numbers?", options: [{ key: "A", text: "4" }, { key: "B", text: "5" }, { key: "C", text: "6" }, { key: "D", text: "8" }], correctKey: "B", explanation: "Mean = sum/n, 8 = 40/n, n = 5." },
  { id: "pq70", topic: "data", difficulty: "hard", question: "5 numbers have mean 10. One number increases by 20. New mean?", options: [{ key: "A", text: "12" }, { key: "B", text: "14" }, { key: "C", text: "16" }, { key: "D", text: "18" }], correctKey: "B", explanation: "Old sum = 50. New sum = 50 + 20 = 70. New mean = 70/5 = 14." },
  // Geometry & more
  { id: "pq71", topic: "geometry", difficulty: "easy", question: "Area of triangle with base 6, height 4?", options: [{ key: "A", text: "10" }, { key: "B", text: "12" }, { key: "C", text: "24" }, { key: "D", text: "48" }], correctKey: "B", explanation: "A = ½bh = ½(6)(4) = 12." },
  { id: "pq72", topic: "geometry", difficulty: "medium", question: "Surface area of cube with edge 3?", options: [{ key: "A", text: "27" }, { key: "B", text: "54" }, { key: "C", text: "81" }, { key: "D", text: "108" }], correctKey: "B", explanation: "6 faces × 9 = 54." },
  { id: "pq73", topic: "geometry", difficulty: "hard", question: "A right triangle has legs 5 and 12. Hypotenuse?", options: [{ key: "A", text: "13" }, { key: "B", text: "17" }, { key: "C", text: "√119" }, { key: "D", text: "7" }], correctKey: "A", explanation: "5²+12²=25+144=169=13²." },
  // Reading
  { id: "pq74", topic: "reading", difficulty: "easy", question: "A narrative passage mainly:", options: [{ key: "A", text: "Tells a story" }, { key: "B", text: "Argues a point" }, { key: "C", text: "Explains a process" }, { key: "D", text: "Compares topics" }], correctKey: "A", explanation: "Narrative = story." },
  { id: "pq75", topic: "reading", difficulty: "medium", question: "When asked about author's purpose, consider:", options: [{ key: "A", text: "Only the first paragraph" }, { key: "B", text: "The whole passage" }, { key: "C", text: "Just the conclusion" }, { key: "D", text: "The title only" }], correctKey: "B", explanation: "Purpose is shown throughout the passage." },
  { id: "pq76", topic: "words", difficulty: "medium", question: "In 'his sardonic smile,' sardonic means:", options: [{ key: "A", text: "warm" }, { key: "B", text: "mocking" }, { key: "C", text: "shy" }, { key: "D", text: "confused" }], correctKey: "B", explanation: "Sardonic = mocking or cynical." },
  { id: "pq77", topic: "grammar", difficulty: "medium", question: "Which uses parallel structure? He likes running, swimming, and ___.", options: [{ key: "A", text: "to bike" }, { key: "B", text: "biking" }, { key: "C", text: "bikes" }, { key: "D", text: "biked" }], correctKey: "B", explanation: "running, swimming, biking—all -ing." },
  { id: "pq78", topic: "evidence", difficulty: "medium", question: "Wrong evidence choices often:", options: [{ key: "A", text: "Support your answer well" }, { key: "B", text: "Sound relevant but don't prove the answer" }, { key: "C", text: "Come from the right paragraph" }, { key: "D", text: "Are too short" }], correctKey: "B", explanation: "Wrong answers sound good but don't actually support your choice." },
  { id: "pq79", topic: "transitions", difficulty: "easy", question: "Which shows cause and effect? ___ it rained, we stayed inside.", options: [{ key: "A", text: "However" }, { key: "B", text: "Because" }, { key: "C", text: "Although" }, { key: "D", text: "Meanwhile" }], correctKey: "B", explanation: "Because shows cause (rain) and effect (stayed inside)." },
  { id: "pq80", topic: "algebra", difficulty: "easy", question: "Solve: 7 - 2x = 1", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "4" }, { key: "D", text: "5" }], correctKey: "B", explanation: "-2x = -6, so x = 3." },
  { id: "pq81", topic: "algebra", difficulty: "medium", question: "If (x-1)(x+2) = 0, which is a solution?", options: [{ key: "A", text: "-1" }, { key: "B", text: "0" }, { key: "C", text: "1" }, { key: "D", text: "2" }], correctKey: "C", explanation: "Roots are 1 and -2; 1 is a solution." },
  { id: "pq82", topic: "quadratics", difficulty: "easy", question: "(x+4)² = ?", options: [{ key: "A", text: "x²+16" }, { key: "B", text: "x²+8x+16" }, { key: "C", text: "x²+4x+16" }, { key: "D", text: "x²+8" }], correctKey: "B", explanation: "(x+4)² = x² + 8x + 16." },
  { id: "pq83", topic: "quadratics", difficulty: "medium", question: "Axis of symmetry of y = x² - 6x + 5 is x = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "6" }], correctKey: "B", explanation: "x = -b/(2a) = 6/2 = 3." },
  { id: "pq84", topic: "functions", difficulty: "easy", question: "If p(x) = 5 - x, then p(3) = ?", options: [{ key: "A", text: "2" }, { key: "B", text: "3" }, { key: "C", text: "5" }, { key: "D", text: "8" }], correctKey: "A", explanation: "p(3) = 5 - 3 = 2." },
  { id: "pq85", topic: "data", difficulty: "easy", question: "Mean of 10, 20, 30?", options: [{ key: "A", text: "15" }, { key: "B", text: "20" }, { key: "C", text: "25" }, { key: "D", text: "60" }], correctKey: "B", explanation: "(10+20+30)/3 = 20." },
  { id: "pq86", topic: "geometry", difficulty: "easy", question: "Volume of cube with edge 4?", options: [{ key: "A", text: "12" }, { key: "B", text: "16" }, { key: "C", text: "64" }, { key: "D", text: "96" }], correctKey: "C", explanation: "V = s³ = 4³ = 64." },
  { id: "pq87", topic: "grammar", difficulty: "easy", question: "Which is correct? 'She and I ___ going.'", options: [{ key: "A", text: "am" }, { key: "B", text: "is" }, { key: "C", text: "are" }, { key: "D", text: "was" }], correctKey: "C", explanation: "Compound subject 'She and I' is plural." },
  { id: "pq88", topic: "words", difficulty: "easy", question: "In 'a prolific writer,' prolific means:", options: [{ key: "A", text: "lazy" }, { key: "B", text: "productive" }, { key: "C", text: "famous" }, { key: "D", text: "old" }], correctKey: "B", explanation: "Prolific = producing much." },
  { id: "pq89", topic: "algebra", difficulty: "hard", question: "If 3x - 2 = 2x + 5, then x = ?", options: [{ key: "A", text: "3" }, { key: "B", text: "5" }, { key: "C", text: "7" }, { key: "D", text: "9" }], correctKey: "C", explanation: "3x - 2x = 5 + 2, so x = 7." },
  { id: "pq90", topic: "algebra", difficulty: "medium", question: "If 4(x - 2) = 2(x + 4), then x = ?", options: [{ key: "A", text: "4" }, { key: "B", text: "6" }, { key: "C", text: "8" }, { key: "D", text: "10" }], correctKey: "C", explanation: "4x-8=2x+8, 2x=16, x=8." },
  { id: "pq91", topic: "quadratics", difficulty: "hard", question: "Discriminant of x² + 4x + 4 = 0?", options: [{ key: "A", text: "0" }, { key: "B", text: "4" }, { key: "C", text: "8" }, { key: "D", text: "16" }], correctKey: "A", explanation: "b²-4ac = 16-16 = 0 (perfect square)." },
  { id: "pq92", topic: "geometry", difficulty: "medium", question: "Area of trapezoid with bases 4 and 6, height 5?", options: [{ key: "A", text: "20" }, { key: "B", text: "25" }, { key: "C", text: "30" }, { key: "D", text: "50" }], correctKey: "B", explanation: "A = ½(4+6)(5) = 25." },
  { id: "pq93", topic: "reading", difficulty: "hard", question: "Inference questions require:", options: [{ key: "A", text: "Exact quotes from the text" }, { key: "B", text: "Logical conclusions from evidence" }, { key: "C", text: "Outside knowledge only" }, { key: "D", text: "The first sentence" }], correctKey: "B", explanation: "Inferences are supported by the passage." },
  { id: "pq94", topic: "grammar", difficulty: "hard", question: "Which is correct? 'The data ___ conclusive.'", options: [{ key: "A", text: "is" }, { key: "B", text: "are" }, { key: "C", text: "was" }, { key: "D", text: "A or B" }], correctKey: "D", explanation: "Data can be singular or plural; both are accepted." },
  { id: "pq95", topic: "transitions", difficulty: "hard", question: "Which signals a conclusion? ___ the evidence supports the theory.", options: [{ key: "A", text: "Furthermore" }, { key: "B", text: "In conclusion" }, { key: "C", text: "For example" }, { key: "D", text: "Similarly" }], correctKey: "B", explanation: "In conclusion signals a summary or ending." },
  { id: "pq96", topic: "algebra", difficulty: "easy", question: "If x + 5 = 12, then x = ?", options: [{ key: "A", text: "5" }, { key: "B", text: "7" }, { key: "C", text: "12" }, { key: "D", text: "17" }], correctKey: "B", explanation: "x = 12 - 5 = 7." },
  { id: "pq97", topic: "functions", difficulty: "medium", question: "Domain of f(x) = 1/(x-2) excludes:", options: [{ key: "A", text: "0" }, { key: "B", text: "1" }, { key: "C", text: "2" }, { key: "D", text: "3" }], correctKey: "C", explanation: "x=2 makes the denominator zero." },
  { id: "pq98", topic: "data", difficulty: "medium", question: "Median of 1, 2, 3, 4, 5, 6?", options: [{ key: "A", text: "3" }, { key: "B", text: "3.5" }, { key: "C", text: "4" }, { key: "D", text: "4.5" }], correctKey: "B", explanation: "Average of 3 and 4 = 3.5." },
  { id: "pq99", topic: "evidence", difficulty: "hard", question: "Best strategy for paired evidence questions:", options: [{ key: "A", text: "Pick evidence first" }, { key: "B", text: "Answer main question first, then find evidence" }, { key: "C", text: "Skip the main question" }, { key: "D", text: "Guess both" }], correctKey: "B", explanation: "Answer first, then find the line that proves it." },
  { id: "pq100", topic: "words", difficulty: "hard", question: "In 'an ambivalent response,' ambivalent means:", options: [{ key: "A", text: "clear" }, { key: "B", text: "mixed feelings" }, { key: "C", text: "negative" }, { key: "D", text: "enthusiastic" }], correctKey: "B", explanation: "Ambivalent = having mixed or conflicting feelings." },
];

const MATH_TOPICS = ["algebra", "quadratics", "functions", "data", "geometry"];
const READING_TOPICS = ["evidence", "words", "reading", "grammar", "transitions"];

export function getQuestionsByTopic(topic: string): PracticeBankQuestion[] {
  if (topic === "math") return PRACTICE_QUESTIONS.filter((q) => MATH_TOPICS.includes(q.topic));
  if (topic === "reading") return PRACTICE_QUESTIONS.filter((q) => READING_TOPICS.includes(q.topic));
  return PRACTICE_QUESTIONS.filter((q) => q.topic === topic);
}

const DIFF_ORDER = { easy: 0, medium: 1, hard: 2 };

/** Returns questions ordered by difficulty (easy → medium → hard), optionally filtered by topic */
export function getQuestionsByDifficultyOrdered(count: number, topic?: string): PracticeBankQuestion[] {
  let pool = topic ? getQuestionsByTopic(topic) : [...PRACTICE_QUESTIONS];
  const sorted = pool.sort((a, b) => DIFF_ORDER[a.difficulty] - DIFF_ORDER[b.difficulty]);
  return sorted.slice(0, Math.min(count, sorted.length));
}

export function getRandomQuestions(count: number, topic?: string): PracticeBankQuestion[] {
  let pool = topic ? getQuestionsByTopic(topic) : [...PRACTICE_QUESTIONS];
  const shuffled = pool.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
